import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {CONVERSATION_QUALITY_CATALOG as rules, CONVERSATION_QUALITY_CATEGORIES as categories, DEFAULT_CONVERSATION_RULE_IDS as defaults, conversationCatalogRules, conversationRuleCategory} from '../src/conversationQualityCatalog.js';
assert.equal(new Set(rules.map(r=>r.id)).size,rules.length);
assert(!rules.some(r=>r.id==='L02'));
assert.deepEqual(categories,['基础质检','隐私质检','场景质检','标签分类']);
assert(rules.every(r=>categories.includes(r.category)&&r.passCriteria&&r.failCriteria));
assert.equal(rules.filter(r=>r.category==='隐私质检'&&!r.example).length,16);
assert(!defaults.includes('S17')&&!defaults.includes('S18'));
assert(!rules.some(r=>r.id==='L08'));
assert(!defaults.includes('L08'));
assert.equal(rules.find(r=>r.id==='L39').category,'标签分类');
assert.equal(conversationRuleCategory({evaluator:'label_coverage'}),'标签分类');
assert.equal(conversationRuleCategory({category:'隐私质检'}),'隐私质检');
const saved=JSON.parse(JSON.stringify({selected_rule_ids:defaults.filter(id=>id!=='L10')}));
assert(!conversationCatalogRules(saved).find(r=>r.id==='L10').enabled);
assert(conversationCatalogRules(saved).find(r=>r.id==='S01').enabled);
assert(conversationCatalogRules({selected_rule_ids:[]}).every(r=>!r.enabled));
console.log('PASS: legacy compatibility categories, unique IDs, privacy examples, and selection round-trip; current MD parity covered by qualityClosedLoop');
