import React,{useEffect,useState} from 'react';
import {Button,Card,Checkbox,Form,Descriptions,Drawer,InputNumber,Radio,Slider,Space,Table,Tooltip,Typography} from 'antd';
import {versionSample} from './taskExecution';
export default function AugmentationSelection({report,total,pool,mode,threshold,onChange,includeUnchecked=false,onIncludeUnchecked,form,limit}){
 const [open,setOpen]=useState(false),[page,setPage]=useState(1);
 useEffect(()=>{if(mode==='score'&&pool.effectiveThreshold!=null&&threshold!==pool.effectiveThreshold)onChange(mode,pool.effectiveThreshold);},[mode,threshold,pool.effectiveThreshold]);
 const chosenCount=pool.count+(includeUnchecked?pool.uncheckedCount:0);
 const ranked=pool.selected.slice().sort((a,b)=>a.score-b.score||a.index-b.index);
 const rows=[];let offset=0;for(const row of ranked){const start=Math.max(0,(page-1)*10-offset),end=Math.min(row.weight,page*10-offset);for(let i=start;i<end;i++){const index=row.index+i*pool.period;rows.push({...row,sampleId:pool.period?versionSample(report.sampleExecution,index).sampleId:row.sampleId});}offset+=row.weight;}
 if(includeUnchecked){for(let rank=Math.max(pool.count,(page-1)*10);rank<Math.min(chosenCount,page*10);rank++){const offset=rank-pool.count;rows.push({sampleId:pool.uncheckedIds?.[offset]||(report?.sampleExecution?versionSample(report.sampleExecution,pool.uncheckedStart+offset).sampleId:'未记录'),score:null,failed:[],unchecked:true});}}
 return <Card className="task-step-card section-title" title="选择增强基础样本" style={{marginBottom:20}}><Typography.Paragraph type="secondary">本次质检报告：{report?.executionRange==='sample'?'抽样检查':'全量检查'} {Number(report?.checkedSampleCount||0).toLocaleString()} / {total.toLocaleString()} 条</Typography.Paragraph><Descriptions column={2} items={[{key:'valid',label:'可参与筛选',children:pool.validCount.toLocaleString()+' 条'},{key:'excluded',label:'未形成完整质量分',children:<Tooltip title={'未抽中 '+(report?.notSelectedSampleCount||0)+' 条；其余为未执行、无法完整判定或无适用规则的样本。'}><span>{Math.max(0,total-pool.validCount).toLocaleString()} 条 ⓘ</span></Tooltip>}]}/>
 <Radio.Group value={mode} onChange={e=>{onChange(e.target.value,pool.maxScore??100);setPage(1);}} options={[{value:'pass',label:'全部适用规则通过（'+pool.passCount.toLocaleString()+' 条）'},{value:'score',label:'按样本质量分筛选'}]}/>
 {mode==='score'&&<div style={{marginTop:20}}><Space wrap><Typography.Text>最低样本质量分 ≥</Typography.Text><InputNumber placeholder="请输入数值" min={pool.minScore??0} max={pool.maxScore??0} disabled={!pool.validCount||pool.minScore===pool.maxScore} precision={2} value={pool.effectiveThreshold} onChange={v=>{onChange(mode,v??pool.maxScore);setPage(1);}}/><Typography.Text type="secondary">中位数：{pool.median==null?'—':pool.median.toFixed(1)+' 分'}</Typography.Text><Button type="link" disabled={pool.median==null} onClick={()=>{onChange(mode,pool.median);setPage(1);}}>使用中位数</Button></Space>{pool.minScore!=null&&pool.minScore!==pool.maxScore?<Slider min={pool.minScore} max={pool.maxScore} marks={{[pool.minScore]:pool.minScore.toFixed(1),[pool.maxScore]:pool.maxScore.toFixed(1)}} step={0.01} value={pool.effectiveThreshold} onChange={v=>{onChange(mode,v);setPage(1);}}/>:<Typography.Paragraph type="secondary" style={{marginTop:12}}>{pool.minScore==null?'暂无可筛选样本':`可筛选样本均为 ${pool.minScore.toFixed(1)} 分，无需调整阈值。`}</Typography.Paragraph>}</div>}
 <div style={{marginTop:16}}><Checkbox checked={includeUnchecked} disabled={!pool.uncheckedCount} onChange={e=>{setPage(1);onIncludeUnchecked?.(e.target.checked);}}>同时纳入未质检样本（{pool.uncheckedCount.toLocaleString()} 条）</Checkbox><div><Typography.Text type="secondary">未质检样本没有质量结论，不受分数阈值限制；已执行但无法判定的样本不纳入。</Typography.Text></div></div>
 <div style={{marginTop:20,padding:16,background:'var(--color-bg-layout, #f5f7fa)',borderRadius:8}}><Space wrap><Typography.Text strong>已选基础样本 {chosenCount.toLocaleString()} 条</Typography.Text><Button type="link" disabled={!chosenCount} onClick={()=>setOpen(true)}>查看样本</Button></Space><div><Typography.Text type="secondary">已质检且符合条件 {pool.count.toLocaleString()} 条 ＋ 未质检 {includeUnchecked?pool.uncheckedCount.toLocaleString():0} 条</Typography.Text></div></div>
 {form&&<div style={{marginTop:20}}><Form.Item name="targetCount" label="增强数量上限" rules={[{required:true},{type:'number',min:1,message:'请输入大于 0 的数量'}]} extra={!chosenCount?'请先选择基础样本':Number(limit)<chosenCount?'从已选基础样本中随机抽取，每条生成 1 条增强样本。':Number(limit)>chosenCount?'候选样本不足时重复采样，每次生成不同增强变体。':'每条基础样本生成 1 条增强样本。'}><InputNumber placeholder="请输入增强数量上限（不小于 1）" min={1} precision={0} addonAfter="条" style={{width:260}}/></Form.Item></div>}
 <Drawer title="增强基础样本 · 按质量分升序" open={open} onClose={()=>setOpen(false)} width={760}><Table rowKey="sampleId" dataSource={rows} pagination={{current:page,pageSize:10,total:chosenCount,onChange:setPage,showSizeChanger:false}} columns={[{title:'样本 ID',dataIndex:'sampleId'},{title:'质量分',dataIndex:'score',render:v=>v==null?'未质检':v.toFixed(1)},{title:'不通过规则',dataIndex:'failed',render:(v,r)=>r.unchecked?'尚无结论':v.join('、')||'无'}]} expandable={{expandedRowRender:r=><pre>{JSON.stringify(report?.sampleResults?.find(s=>s.sampleId===r.sampleId)||r,null,2)}</pre>}}/></Drawer></Card>;
}
