// Rule definitions transcribed from 02_逐类质检规则.md. These are configuration, not executed results.
export const CONVERSATION_QUALITY_CATEGORIES = ['基础质检', '隐私质检', '场景质检', '标签分类'];
export const CONVERSATION_QUALITY_CATALOG = [
  {
    "id": "S01",
    "rule_id": "S01",
    "name": "中国身份证号检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "中国身份证号候选",
    "engine": "P0 · Dingo cn_id_card；厦门一期“PI敏感信息检测”“身份证信息检测”",
    "severity": "BLOCK",
    "description": "中国身份证号候选",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在未处置命中或处置后仍残留",
    "priority": "P0",
    "source": "P0 · Dingo cn_id_card；厦门一期“PI敏感信息检测”“身份证信息检测”",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S02",
    "rule_id": "S02",
    "name": "中国手机号检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "中国手机号候选",
    "engine": "P0 · Dingo cn_phone；厦门一期“PI敏感信息检测”",
    "severity": "BLOCK",
    "description": "中国手机号候选",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在未处置命中或处置后仍残留",
    "priority": "P0",
    "source": "P0 · Dingo cn_phone；厦门一期“PI敏感信息检测”",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S03",
    "rule_id": "S03",
    "name": "邮箱检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "邮箱地址",
    "engine": "P0 · Dingo email；厦门一期“PI敏感信息检测”",
    "severity": "BLOCK",
    "description": "邮箱地址",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在未处置命中或处置后仍残留",
    "priority": "P0",
    "source": "P0 · Dingo email；厦门一期“PI敏感信息检测”",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S04",
    "rule_id": "S04",
    "name": "信用卡号检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "信用卡号候选",
    "engine": "P0 · Dingo credit_card；厦门一期“PI敏感信息检测”",
    "severity": "BLOCK",
    "description": "信用卡号候选",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在未处置命中或处置后仍残留",
    "priority": "P0",
    "source": "P0 · Dingo credit_card；厦门一期“PI敏感信息检测”",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S05",
    "rule_id": "S05",
    "name": "中国护照号检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "中国护照号候选",
    "engine": "P0 · Dingo cn_passport；厦门一期表格未逐项证明",
    "severity": "BLOCK",
    "description": "中国护照号候选",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在未处置命中或处置后仍残留",
    "priority": "P0",
    "source": "P0 · Dingo cn_passport；厦门一期表格未逐项证明",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S06",
    "rule_id": "S06",
    "name": "美国SSN检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "美国社会安全号码候选",
    "engine": "P0 · Dingo ssn；厦门一期表格未逐项证明",
    "severity": "BLOCK",
    "description": "美国社会安全号码候选",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在未处置命中或处置后仍残留",
    "priority": "P0",
    "source": "P0 · Dingo ssn；厦门一期表格未逐项证明",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S07",
    "rule_id": "S07",
    "name": "IPv4地址检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "IPv4地址候选及上下文",
    "engine": "P0 · Dingo ip_address；厦门一期表格未逐项证明",
    "severity": "BLOCK",
    "description": "IPv4地址候选及上下文",
    "passCriteria": "命中符合模板允许范围，或需处置内容已处理",
    "failCriteria": "存在模板禁止且未处理的地址",
    "priority": "P0",
    "source": "P0 · Dingo ip_address；厦门一期表格未逐项证明",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S08",
    "rule_id": "S08",
    "name": "详细地址候选检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "详细地址候选；规则匹配地址要素组合，大模型方式可结合上下文判断",
    "engine": "P0 · Dingo RuleResumeDetailedAddress；LLMResumeQuality 的 Error_Detailed_Address 提供大模型检查方式；厦门一期“简历详细地址检测”。Dingo 原为简历场景，跨类型需适配，不等于GPS检测",
    "severity": "BLOCK",
    "description": "详细地址候选；规则匹配地址要素组合，大模型方式可结合上下文判断",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在未处置命中或处置后仍残留",
    "priority": "P0",
    "source": "P0 · Dingo RuleResumeDetailedAddress；LLMResumeQuality 的 Error_Detailed_Address 提供大模型检查方式；厦门一期“简历详细地址检测”。Dingo 原为简历场景，跨类型需适配，不等于GPS检测",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S09",
    "rule_id": "S09",
    "name": "姓名检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "姓名字段及文本中的姓名候选；不判断是否对应真实个人，不检查与其他实体的关联隐私",
    "engine": "P1 · 用户确认的姓名检测需求；本地Dingo未发现专用规则",
    "severity": "BLOCK",
    "description": "姓名字段及文本中的姓名候选；不判断是否对应真实个人，不检查与其他实体的关联隐私",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在需处置但未处置的姓名命中或处置后仍残留",
    "priority": "P1",
    "source": "P1 · 用户确认的姓名检测需求；本地Dingo未发现专用规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S10",
    "rule_id": "S10",
    "name": "车牌号检测与处置",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "车牌号及关联信息",
    "engine": "P1 · 原型联系位置规则",
    "severity": "BLOCK",
    "description": "车牌号及关联信息",
    "passCriteria": "符合模板策略或已完成处置",
    "failCriteria": "存在未处置的禁止信息",
    "priority": "P1",
    "source": "P1 · 原型联系位置规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S11",
    "rule_id": "S11",
    "name": "企业名称检测",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "经营单位、收货单位、申报单位等字段，以及正文、印章中的企业名称候选；不判断企业是否真实存在",
    "engine": "P1 · 用户确认的业务主体信息保护需求；本地Dingo未发现专用规则",
    "severity": "BLOCK",
    "description": "经营单位、收货单位、申报单位等字段，以及正文、印章中的企业名称候选；不判断企业是否真实存在",
    "passCriteria": "无需处置的命中，或按模板策略处置并复检通过",
    "failCriteria": "存在需处置但未处置的企业名称命中或处置后仍残留",
    "priority": "P1",
    "source": "P1 · 用户确认的业务主体信息保护需求；本地Dingo未发现专用规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S12",
    "rule_id": "S12",
    "name": "真实运单号检测与处置",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "运单号候选及关联信息",
    "engine": "P1 · 原型业务标识规则",
    "severity": "BLOCK",
    "description": "运单号候选及关联信息",
    "passCriteria": "符合模板业务标识策略或已完成处置",
    "failCriteria": "存在未处置的禁止业务标识",
    "priority": "P1",
    "source": "P1 · 原型业务标识规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S13",
    "rule_id": "S13",
    "name": "API Key检测与处置",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "API密钥候选",
    "engine": "P1 · 原型密钥规则",
    "severity": "BLOCK",
    "description": "API密钥候选",
    "passCriteria": "符合模板示例值策略或已完成处置",
    "failCriteria": "存在未处置的禁止密钥候选",
    "priority": "P1",
    "source": "P1 · 原型密钥规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S14",
    "rule_id": "S14",
    "name": "Token检测与处置",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "访问令牌候选",
    "engine": "P1 · 原型密钥规则",
    "severity": "BLOCK",
    "description": "访问令牌候选",
    "passCriteria": "符合模板示例值策略或已完成处置",
    "failCriteria": "存在未处置的禁止令牌候选",
    "priority": "P1",
    "source": "P1 · 原型密钥规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S15",
    "rule_id": "S15",
    "name": "Cookie检测与处置",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "Cookie中的认证或敏感值",
    "engine": "P1 · 原型密钥规则",
    "severity": "BLOCK",
    "description": "Cookie中的认证或敏感值",
    "passCriteria": "符合模板策略或已完成处置",
    "failCriteria": "存在未处置的敏感Cookie值",
    "priority": "P1",
    "source": "P1 · 原型密钥规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S16",
    "rule_id": "S16",
    "name": "密码检测与处置",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "密码及上下文",
    "engine": "P1 · 原型密钥规则",
    "severity": "BLOCK",
    "description": "密码及上下文",
    "passCriteria": "符合模板示例值策略或已完成处置",
    "failCriteria": "存在未处置的禁止密码内容",
    "priority": "P1",
    "source": "P1 · 原型密钥规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "S17",
    "rule_id": "S17",
    "name": "真实客户/内部账号检测与处置",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "用户定义的客户编号、内部账号格式及敏感范围",
    "engine": "P1 · 用户自定义隐私检查规则示例，非通用隐私检查",
    "severity": "BLOCK",
    "description": "用户定义的客户编号、内部账号格式及敏感范围",
    "passCriteria": "符合模板业务标识策略或已完成处置",
    "failCriteria": "存在未处置的禁止业务标识",
    "priority": "P1",
    "source": "P1 · 用户自定义隐私检查规则示例，非通用隐私检查",
    "xiamen": "详见02文档",
    "example": true,
    "enabled": false
  },
  {
    "id": "S18",
    "rule_id": "S18",
    "name": "设备标识关联隐私",
    "category": "隐私质检",
    "scope": "事件 + 全部消息",
    "target": "用户定义的设备标识格式、主体关联关系及敏感范围",
    "engine": "P1 · 用户自定义隐私检查规则示例，非通用隐私检查",
    "severity": "BLOCK",
    "description": "用户定义的设备标识格式、主体关联关系及敏感范围",
    "passCriteria": "符合模板实体保护策略或已完成处置",
    "failCriteria": "存在未处置的敏感关联",
    "priority": "P1",
    "source": "P1 · 用户自定义隐私检查规则示例，非通用隐私检查",
    "xiamen": "详见02文档",
    "example": true,
    "enabled": false
  },
  {
    "id": "L10",
    "rule_id": "L10",
    "name": "消息正文非空",
    "category": "基础质检",
    "scope": "应有正文的消息文本；不对合法的纯工具调用消息强制要求正文",
    "target": "应有正文的消息文本；不对合法的纯工具调用消息强制要求正文",
    "engine": "RuleContentNull",
    "severity": "REVIEW",
    "description": "应有正文的消息文本；不对合法的纯工具调用消息强制要求正文",
    "passCriteria": "去除空白后仍有文本",
    "failCriteria": "应有正文却为空",
    "priority": "P0",
    "source": "RuleContentNull",
    "xiamen": "有：空内容检测（91）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L11",
    "rule_id": "L11",
    "name": "字符长度",
    "category": "基础质检",
    "scope": "单条消息或选定文本的字符数",
    "target": "单条消息或选定文本的字符数",
    "engine": "RuleCharNumber、RuleContentShort、RuleContentShortMultiLan；按语言选实现",
    "severity": "REVIEW",
    "description": "单条消息或选定文本的字符数",
    "passCriteria": "满足配置的字符长度下限",
    "failCriteria": "字符数低于下限",
    "priority": "P0",
    "source": "RuleCharNumber、RuleContentShort、RuleContentShortMultiLan；按语言选实现",
    "xiamen": "有：字符数量检查（87）、内容过短检测（93）、多语言内容过短检测（95）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L12",
    "rule_id": "L12",
    "name": "乱码与不可读字符",
    "category": "基础质检",
    "scope": "正文中的编码乱码、破损字符",
    "target": "正文中的编码乱码、破损字符",
    "engine": "LLMTextChaos、LLMTextUnreadIssue；合并同目标检测",
    "severity": "REVIEW",
    "description": "正文中的编码乱码、破损字符",
    "passCriteria": "乱码程度在任务允许范围内",
    "failCriteria": "乱码导致不可读或超过允许范围",
    "priority": "P0",
    "source": "LLMTextChaos、LLMTextUnreadIssue；合并同目标检测",
    "xiamen": "有：文本乱码检测（50）、文本不可读问题检测（68）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L13",
    "rule_id": "L13",
    "name": "不可见字符",
    "category": "基础质检",
    "scope": "正文中配置范围内的不可见字符",
    "target": "正文中配置范围内的不可见字符",
    "engine": "RuleInvisibleChar",
    "severity": "REVIEW",
    "description": "正文中配置范围内的不可见字符",
    "passCriteria": "命中占比不超过阈值",
    "failCriteria": "占比超过阈值",
    "priority": "P0",
    "source": "RuleInvisibleChar",
    "xiamen": "有：不可见字符检测（123）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L14",
    "rule_id": "L14",
    "name": "特殊字符过多",
    "category": "基础质检",
    "scope": "正文中特殊字符占比",
    "target": "正文中特殊字符占比",
    "engine": "RuleSpecialCharacter",
    "severity": "REVIEW",
    "description": "正文中特殊字符占比",
    "passCriteria": "不超过配置阈值",
    "failCriteria": "超过阈值",
    "priority": "P0",
    "source": "RuleSpecialCharacter",
    "xiamen": "有：特殊字符过多检测（153）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L15",
    "rule_id": "L15",
    "name": "连续空格过多",
    "category": "基础质检",
    "scope": "文本中连续空格",
    "target": "文本中连续空格",
    "engine": "RuleSpaceMore",
    "severity": "REVIEW",
    "description": "文本中连续空格",
    "passCriteria": "未达到配置的异常条件",
    "failCriteria": "连续空格达到异常条件",
    "priority": "P0",
    "source": "RuleSpaceMore",
    "xiamen": "有：连续空格过多检测（152）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L16",
    "rule_id": "L16",
    "name": "连续换行过多",
    "category": "基础质检",
    "scope": "文本中连续换行",
    "target": "文本中连续换行",
    "engine": "RuleEnterMore",
    "severity": "REVIEW",
    "description": "文本中连续换行",
    "passCriteria": "不超过配置限制",
    "failCriteria": "连续换行超过限制",
    "priority": "P0",
    "source": "RuleEnterMore",
    "xiamen": "有：连续回车检测（102）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L17",
    "rule_id": "L17",
    "name": "换行占比",
    "category": "基础质检",
    "scope": "正文中的换行比例",
    "target": "正文中的换行比例",
    "engine": "RuleEnterRatioMore",
    "severity": "REVIEW",
    "description": "正文中的换行比例",
    "passCriteria": "比例在配置范围内",
    "failCriteria": "比例超过限制",
    "priority": "P0",
    "source": "RuleEnterRatioMore",
    "xiamen": "有：回车占比检查（103）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L18",
    "rule_id": "L18",
    "name": "HTML实体残留",
    "category": "基础质检",
    "scope": "自然语言正文中的HTML转义实体",
    "target": "自然语言正文中的HTML转义实体",
    "engine": "RuleHtmlEntity",
    "severity": "REVIEW",
    "description": "自然语言正文中的HTML转义实体",
    "passCriteria": "不存在模板禁止的实体残留",
    "failCriteria": "命中禁止的残留",
    "priority": "P0",
    "source": "RuleHtmlEntity",
    "xiamen": "有：HTML实体检测（112）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L19",
    "rule_id": "L19",
    "name": "HTML标签残留",
    "category": "基础质检",
    "scope": "自然语言正文中的HTML标签；代码或HTML教学按模板豁免",
    "target": "自然语言正文中的HTML标签；代码或HTML教学按模板豁免",
    "engine": "RuleHtmlTag",
    "severity": "REVIEW",
    "description": "自然语言正文中的HTML标签；代码或HTML教学按模板豁免",
    "passCriteria": "不存在模板禁止的标签残留",
    "failCriteria": "命中禁止的残留",
    "priority": "P0",
    "source": "RuleHtmlTag",
    "xiamen": "有：HTML标签检测（113）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L20",
    "rule_id": "L20",
    "name": "异常字符拆分",
    "category": "基础质检",
    "scope": "本应连续的文本被异常空格或分隔符拆开",
    "target": "本应连续的文本被异常空格或分隔符拆开",
    "engine": "RuleCharSplit",
    "severity": "REVIEW",
    "description": "本应连续的文本被异常空格或分隔符拆开",
    "passCriteria": "未检出异常拆分",
    "failCriteria": "检出影响阅读的拆分",
    "priority": "P0",
    "source": "RuleCharSplit",
    "xiamen": "有：PII字符串拆分检测（88）；此项是文本拆分，不是隐私识别",
    "example": false,
    "enabled": true
  },
  {
    "id": "L21",
    "rule_id": "L21",
    "name": "异常单词拆分",
    "category": "基础质检",
    "scope": "词内部的错误断开；适用于有词边界的语言",
    "target": "词内部的错误断开；适用于有词边界的语言",
    "engine": "RuleWordSplit",
    "severity": "REVIEW",
    "description": "词内部的错误断开；适用于有词边界的语言",
    "passCriteria": "未检出异常断词",
    "failCriteria": "检出异常断词",
    "priority": "P0",
    "source": "RuleWordSplit",
    "xiamen": "有：异常单词拆分检测（160）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L22",
    "rule_id": "L22",
    "name": "词语粘连",
    "category": "基础质检",
    "scope": "缺少词间分隔导致的粘连",
    "target": "缺少词间分隔导致的粘连",
    "engine": "RuleWordStuck、LLMTextWordStick；规则和模型为替代实现",
    "severity": "REVIEW",
    "description": "缺少词间分隔导致的粘连",
    "passCriteria": "无不符合语言规则的粘连",
    "failCriteria": "存在异常粘连",
    "priority": "P0",
    "source": "RuleWordStuck、LLMTextWordStick；规则和模型为替代实现",
    "xiamen": "有：词语粘连检测（161）、文本词语粘连检测（69）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L23",
    "rule_id": "L23",
    "name": "正文重复",
    "category": "基础质检",
    "scope": "同条消息或整段会话中无意义的重复；范围须明确",
    "target": "同条消息或整段会话中无意义的重复；范围须明确",
    "engine": "RuleDocRepeat、LLMTextRepeat；不等于跨样本去重",
    "severity": "REVIEW",
    "description": "同条消息或整段会话中无意义的重复；范围须明确",
    "passCriteria": "重复程度不超过任务阈值",
    "failCriteria": "无意义重复超过阈值",
    "priority": "P0",
    "source": "RuleDocRepeat、LLMTextRepeat；不等于跨样本去重",
    "xiamen": "有：文档重复内容检测（99）、文本重复内容检测（66）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L24",
    "rule_id": "L24",
    "name": "占位文本残留",
    "category": "基础质检",
    "scope": "Lorem Ipsum等配置的占位文本",
    "target": "Lorem Ipsum等配置的占位文本",
    "engine": "RuleLoremIpsum",
    "severity": "REVIEW",
    "description": "Lorem Ipsum等配置的占位文本",
    "passCriteria": "未命中禁止的占位文本",
    "failCriteria": "命中禁止的占位文本",
    "priority": "P0",
    "source": "RuleLoremIpsum",
    "xiamen": "有：Lorem Ipsum占位符检测（130）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L25",
    "rule_id": "L25",
    "name": "纯URL正文",
    "category": "基础质检",
    "scope": "仅包含URL而没有有效说明的消息",
    "target": "仅包含URL而没有有效说明的消息",
    "engine": "RuleOnlyUrl",
    "severity": "REVIEW",
    "description": "仅包含URL而没有有效说明的消息",
    "passCriteria": "不属于模板禁止的纯URL回复",
    "failCriteria": "命中禁止的纯URL回复",
    "priority": "P0",
    "source": "RuleOnlyUrl",
    "xiamen": "有：仅URL内容检测（134）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L26",
    "rule_id": "L26",
    "name": "文本来源/水印残留",
    "category": "基础质检",
    "scope": "采集或转换残留的来源水印词；不检查合成图片交付水印",
    "target": "采集或转换残留的来源水印词；不检查合成图片交付水印",
    "engine": "RuleWatermark",
    "severity": "REVIEW",
    "description": "采集或转换残留的来源水印词；不检查合成图片交付水印",
    "passCriteria": "未命中禁止的残留词",
    "failCriteria": "命中禁止的残留词",
    "priority": "P0",
    "source": "RuleWatermark",
    "xiamen": "有：水印检测（158）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L27",
    "rule_id": "L27",
    "name": "禁止词命中",
    "category": "基础质检",
    "scope": "模板指定的禁止词及词表",
    "target": "模板指定的禁止词及词表",
    "engine": "RuleUnsafeWords；必须配置词表",
    "severity": "REVIEW",
    "description": "模板指定的禁止词及词表",
    "passCriteria": "未命中禁止词",
    "failCriteria": "命中禁止词",
    "priority": "P0",
    "source": "RuleUnsafeWords；必须配置词表",
    "xiamen": "有：不安全词汇检测（157）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L28",
    "rule_id": "L28",
    "name": "违禁内容",
    "category": "基础质检",
    "scope": "正文中的违禁语义",
    "target": "正文中的违禁语义",
    "engine": "LLMSecurityProhibition",
    "severity": "REVIEW",
    "description": "正文中的违禁语义",
    "passCriteria": "符合任务采用的内容安全标准",
    "failCriteria": "触犯所选安全标准",
    "priority": "P0",
    "source": "LLMSecurityProhibition",
    "xiamen": "有：违禁内容检测（45）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L29",
    "rule_id": "L29",
    "name": "涉政内容",
    "category": "基础质检",
    "scope": "正文是否命中所选涉政策略",
    "target": "正文是否命中所选涉政策略",
    "engine": "LLMSecurityPolitics",
    "severity": "REVIEW",
    "description": "正文是否命中所选涉政策略",
    "passCriteria": "符合模板允许范围",
    "failCriteria": "命中模板禁止范围；不把所有政治主题统一判坏",
    "priority": "P0",
    "source": "LLMSecurityPolitics",
    "xiamen": "有：涉政内容检测（44）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L30",
    "rule_id": "L30",
    "name": "回答有害性",
    "category": "基础质检",
    "scope": "问题与回答中可能造成伤害的建议",
    "target": "问题与回答中可能造成伤害的建议",
    "engine": "LLMText3HHarmless；与禁止词、违禁分类分别衡量",
    "severity": "REVIEW",
    "description": "问题与回答中可能造成伤害的建议",
    "passCriteria": "有害性评估符合标准",
    "failCriteria": "给出不符合标准的有害建议",
    "priority": "P0",
    "source": "LLMText3HHarmless；与禁止词、违禁分类分别衡量",
    "xiamen": "有：3H有害性评估（47）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L31",
    "rule_id": "L31",
    "name": "攻击性/毒性语言",
    "category": "基础质检",
    "scope": "辱骂、威胁、身份攻击等毒性评分",
    "target": "辱骂、威胁、身份攻击等毒性评分",
    "engine": "LLMPerspective；需外部API服务",
    "severity": "REVIEW",
    "description": "辱骂、威胁、身份攻击等毒性评分",
    "passCriteria": "所选毒性属性不超过阈值",
    "failCriteria": "任一必检属性超阈值",
    "priority": "P0",
    "source": "LLMPerspective；需外部API服务",
    "xiamen": "未能确认：文本观点立场评估（35）描述并非毒性检测",
    "example": false,
    "enabled": true
  },
  {
    "id": "L07",
    "rule_id": "L07",
    "name": "回答与问题相关",
    "category": "基础质检",
    "scope": "当前问题及其上下文与对应回答",
    "target": "当前问题及其上下文与对应回答",
    "engine": "LLMRAGAnswerRelevancy；将会话转为问题/回答输入",
    "severity": "REVIEW",
    "description": "当前问题及其上下文与对应回答",
    "passCriteria": "相关性分数达到任务标准",
    "failCriteria": "答非所问或相关性未达标",
    "priority": "P0",
    "source": "LLMRAGAnswerRelevancy；将会话转为问题/回答输入",
    "xiamen": "有：RAG答案相关性（36）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L32",
    "rule_id": "L32",
    "name": "回答有用性",
    "category": "基础质检",
    "scope": "回答是否提供有效帮助和足够信息",
    "target": "回答是否提供有效帮助和足够信息",
    "engine": "LLMText3HHelpful",
    "severity": "REVIEW",
    "description": "回答是否提供有效帮助和足够信息",
    "passCriteria": "有用性达到任务标准",
    "failCriteria": "虽相关但无法有效帮助用户或信息不足",
    "priority": "P0",
    "source": "LLMText3HHelpful",
    "xiamen": "有：3H有用性评估（48）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L33",
    "rule_id": "L33",
    "name": "回答诚实性",
    "category": "基础质检",
    "scope": "回答是否虚构能力、证据或隐瞒不确定性",
    "target": "回答是否虚构能力、证据或隐瞒不确定性",
    "engine": "LLMText3HHonest",
    "severity": "REVIEW",
    "description": "回答是否虚构能力、证据或隐瞒不确定性",
    "passCriteria": "诚实性符合任务标准",
    "failCriteria": "虚构依据、能力或不当宣称确定",
    "priority": "P0",
    "source": "LLMText3HHonest",
    "xiamen": "有：3H诚实性评估（49）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L34",
    "rule_id": "L34",
    "name": "依据支持与幻觉",
    "category": "基础质检",
    "scope": "回答中的事实是否被冻结事件、有效工具结果或给定知识支持",
    "target": "回答中的事实是否被冻结事件、有效工具结果或给定知识支持",
    "engine": "LLMRAGFaithfulness、LLMHallucination、RuleHallucinationHHEM；固定选用方法及判分口径，不重复计分",
    "severity": "REVIEW",
    "description": "回答中的事实是否被冻结事件、有效工具结果或给定知识支持",
    "passCriteria": "依据支持度达到标准，且无超出标准的矛盾/无依据断言",
    "failCriteria": "存在超限的矛盾或无依据事实",
    "priority": "P0",
    "source": "LLMRAGFaithfulness、LLMHallucination、RuleHallucinationHHEM；固定选用方法及判分口径，不重复计分",
    "xiamen": "有：RAG答案忠实度（40）、LLM幻觉检测（16）；未证明已接入本地模型版",
    "example": false,
    "enabled": true
  },
  {
    "id": "L35",
    "rule_id": "L35",
    "name": "公共事实核查",
    "category": "基础质检",
    "scope": "对话中可公开查证的事实断言；仅选公共知识内容",
    "target": "对话中可公开查证的事实断言；仅选公共知识内容",
    "engine": "LLMFactCheckPublic、AgentFactCheck、AgentHallucination、ArticleFactChecker；按输入长度和证据模式选择",
    "severity": "REVIEW",
    "description": "对话中可公开查证的事实断言；仅选公共知识内容",
    "passCriteria": "按可信证据核验达到标准",
    "failCriteria": "证据反驳或未达到标准；证据不足单列待确认",
    "priority": "P0",
    "source": "LLMFactCheckPublic、AgentFactCheck、AgentHallucination、ArticleFactChecker；按输入长度和证据模式选择",
    "xiamen": "有：高阶段事实性评估（14）、智能体事实核查（2）、智能体幻觉检测（3）、文章语事实核查（4）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L36",
    "rule_id": "L36",
    "name": "AI腔/模板化表达",
    "category": "基础质检",
    "scope": "套话、刻意升华、过度修饰等表达",
    "target": "套话、刻意升华、过度修饰等表达",
    "engine": "LLMAISmell；不是判断是否由AI生成",
    "severity": "REVIEW",
    "description": "套话、刻意升华、过度修饰等表达",
    "passCriteria": "符合目标风格和任务阈值",
    "failCriteria": "模板化表达程度超限",
    "priority": "P0",
    "source": "LLMAISmell；不是判断是否由AI生成",
    "xiamen": "有：AI味检测（29）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L37",
    "rule_id": "L37",
    "name": "生成指令清晰度",
    "category": "基础质检",
    "scope": "事件中的synthesis_instruction及必要约束",
    "target": "事件中的synthesis_instruction及必要约束",
    "engine": "LLMInstructionClarity；检查生成前指令，不替代回答遵循度",
    "severity": "REVIEW",
    "description": "事件中的synthesis_instruction及必要约束",
    "passCriteria": "指令清晰、具体且可执行，达到任务标准",
    "failCriteria": "含糊、冲突或缺少关键要求",
    "priority": "P0",
    "source": "LLMInstructionClarity；检查生成前指令，不替代回答遵循度",
    "xiamen": "有：指令遵循度评估（23），表中描述实际是指令清晰度",
    "example": false,
    "enabled": true
  },
  {
    "id": "L38",
    "rule_id": "L38",
    "name": "任务难度匹配",
    "category": "基础质检",
    "scope": "事件指令/问题的任务难度",
    "target": "事件指令/问题的任务难度",
    "engine": "LLMTaskDifficulty；难度高低本身不是质量好坏",
    "severity": "REVIEW",
    "description": "事件指令/问题的任务难度",
    "passCriteria": "评估难度落在模板指定档位",
    "failCriteria": "难度与目标档位不符",
    "priority": "P0",
    "source": "LLMTaskDifficulty；难度高低本身不是质量好坏",
    "xiamen": "有：任务难度评估（46）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L39",
    "rule_id": "L39",
    "name": "文本主题匹配",
    "category": "标签分类",
    "scope": "消息文本的主题分类",
    "target": "消息文本的主题分类",
    "engine": "LLMClassifyTopic；须增加目标分类到通过标准的映射",
    "severity": "REVIEW",
    "description": "消息文本的主题分类",
    "passCriteria": "分类符合模板允许主题",
    "failCriteria": "落入禁止或非目标主题",
    "priority": "P0",
    "source": "LLMClassifyTopic；须增加目标分类到通过标准的映射",
    "xiamen": "有：文本主题分类（9）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L40",
    "rule_id": "L40",
    "name": "文本困惑度",
    "category": "基础质检",
    "scope": "指定语言模型对正文的困惑度",
    "target": "指定语言模型对正文的困惑度",
    "engine": "Rule_TC609_02080101_TextPerplexity；不直接代表事实正确性",
    "severity": "REVIEW",
    "description": "指定语言模型对正文的困惑度",
    "passCriteria": "不超过经场景校准的阈值",
    "failCriteria": "超过阈值",
    "priority": "P0",
    "source": "Rule_TC609_02080101_TextPerplexity；不直接代表事实正确性",
    "xiamen": "表中未见独立对应项",
    "example": false,
    "enabled": true
  },
  {
    "id": "L41",
    "rule_id": "L41",
    "name": "工具选择正确性",
    "category": "基础质检",
    "scope": "实际调用的工具与业务目标",
    "target": "实际调用的工具与业务目标",
    "engine": "LLMAgentToolCorrectness",
    "severity": "REVIEW",
    "description": "实际调用的工具与业务目标",
    "passCriteria": "工具选择必要且合适，达到任务标准",
    "failCriteria": "调用不适当工具或遗漏必要工具",
    "priority": "P0",
    "source": "LLMAgentToolCorrectness",
    "xiamen": "有：智能体工具调用正确性（24）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L42",
    "rule_id": "L42",
    "name": "工具参数正确性",
    "category": "基础质检",
    "scope": "调用参数与事件事实、上下文及工具要求",
    "target": "调用参数与事件事实、上下文及工具要求",
    "engine": "LLMAgentArgumentCorrectness",
    "severity": "REVIEW",
    "description": "调用参数与事件事实、上下文及工具要求",
    "passCriteria": "参数语义正确且符合约束",
    "failCriteria": "参数取值、关联事实或必要参数错误",
    "priority": "P0",
    "source": "LLMAgentArgumentCorrectness",
    "xiamen": "相关：智能体工具调用正确性（24）含参数；智能体论证正确性（13）描述不同，不能证明等价",
    "example": false,
    "enabled": true
  },
  {
    "id": "L43",
    "rule_id": "L43",
    "name": "错误恢复能力",
    "category": "基础质检",
    "scope": "真实轨迹中工具报错后的处理",
    "target": "真实轨迹中工具报错后的处理",
    "engine": "LLMAgentErrorRecovery",
    "severity": "REVIEW",
    "description": "真实轨迹中工具报错后的处理",
    "passCriteria": "按任务要求恢复或合理终止",
    "failCriteria": "未恢复、错误扩散或处理不当",
    "priority": "P0",
    "source": "LLMAgentErrorRecovery",
    "xiamen": "有：智能体错误恢复能力（15）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L44",
    "rule_id": "L44",
    "name": "计划遵循度",
    "category": "基础质检",
    "scope": "预期计划与实际步骤轨迹",
    "target": "预期计划与实际步骤轨迹",
    "engine": "LLMAgentPlanAdherence",
    "severity": "REVIEW",
    "description": "预期计划与实际步骤轨迹",
    "passCriteria": "实际步骤符合允许的计划及调整规则",
    "failCriteria": "无合理原因偏离计划",
    "priority": "P0",
    "source": "LLMAgentPlanAdherence",
    "xiamen": "有：智能体计划遵循度（17）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L45",
    "rule_id": "L45",
    "name": "计划质量",
    "category": "基础质检",
    "scope": "事件计划/智能体计划对目标的可执行性",
    "target": "事件计划/智能体计划对目标的可执行性",
    "engine": "LLMAgentPlanQuality",
    "severity": "REVIEW",
    "description": "事件计划/智能体计划对目标的可执行性",
    "passCriteria": "计划可执行且达到评分标准",
    "failCriteria": "缺关键步骤、顺序不合理或不可执行",
    "priority": "P0",
    "source": "LLMAgentPlanQuality",
    "xiamen": "有：智能体计划质量（19）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L46",
    "rule_id": "L46",
    "name": "步骤效率",
    "category": "基础质检",
    "scope": "实际执行轨迹中的冗余步骤",
    "target": "实际执行轨迹中的冗余步骤",
    "engine": "LLMAgentStepEfficiency",
    "severity": "REVIEW",
    "description": "实际执行轨迹中的冗余步骤",
    "passCriteria": "效率评分达到要求",
    "failCriteria": "存在超出容许范围的无效步骤",
    "priority": "P0",
    "source": "LLMAgentStepEfficiency",
    "xiamen": "有：智能体步骤效率（20）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L47",
    "rule_id": "L47",
    "name": "任务完成度",
    "category": "基础质检",
    "scope": "实际对话结果与事件目标及预期终态",
    "target": "实际对话结果与事件目标及预期终态",
    "engine": "LLMAgentTaskCompletion",
    "severity": "REVIEW",
    "description": "实际对话结果与事件目标及预期终态",
    "passCriteria": "完成度达到任务标准",
    "failCriteria": "未达到目标或预期终态",
    "priority": "P0",
    "source": "LLMAgentTaskCompletion",
    "xiamen": "有：智能体任务完成度（22）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L48",
    "rule_id": "L48",
    "name": "轨迹结论质量",
    "category": "基础质检",
    "scope": "最终总结对实际执行过程及结果的反映",
    "target": "最终总结对实际执行过程及结果的反映",
    "engine": "LLMAgentTraceConclusion",
    "severity": "REVIEW",
    "description": "最终总结对实际执行过程及结果的反映",
    "passCriteria": "结论准确完整反映轨迹",
    "failCriteria": "结论遗漏、误述或夸大执行结果",
    "priority": "P0",
    "source": "LLMAgentTraceConclusion",
    "xiamen": "有：智能体轨迹结论质量（26）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L49",
    "rule_id": "L49",
    "name": "工具调用循环",
    "category": "基础质检",
    "scope": "实际工具调用序列的重复模式",
    "target": "实际工具调用序列的重复模式",
    "engine": "RuleAgentTraceLoopDetection",
    "severity": "REVIEW",
    "description": "实际工具调用序列的重复模式",
    "passCriteria": "无达到检测条件的异常循环",
    "failCriteria": "出现达到条件的重复调用循环",
    "priority": "P0",
    "source": "RuleAgentTraceLoopDetection",
    "xiamen": "有：智能体轨迹死循环检测（92）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L50",
    "rule_id": "L50",
    "name": "轨迹Token预算",
    "category": "基础质检",
    "scope": "执行轨迹记录的Token消耗",
    "target": "执行轨迹记录的Token消耗",
    "engine": "RuleAgentTraceTokenBudget；需真实用量记录",
    "severity": "REVIEW",
    "description": "执行轨迹记录的Token消耗",
    "passCriteria": "不超过任务预算",
    "failCriteria": "超过预算",
    "priority": "P0",
    "source": "RuleAgentTraceTokenBudget；需真实用量记录",
    "xiamen": "有：智能体轨迹Token预算检查（94）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L51",
    "rule_id": "L51",
    "name": "轨迹延迟异常",
    "category": "基础质检",
    "scope": "执行步骤的真实耗时",
    "target": "执行步骤的真实耗时",
    "engine": "RuleAgentTraceLatencyAnomaly；需真实耗时",
    "severity": "REVIEW",
    "description": "执行步骤的真实耗时",
    "passCriteria": "未达到配置的延迟异常条件",
    "failCriteria": "达到异常条件",
    "priority": "P0",
    "source": "RuleAgentTraceLatencyAnomaly；需真实耗时",
    "xiamen": "有：智能体轨迹延迟异常检测（90）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L52",
    "rule_id": "L52",
    "name": "检索上下文相关性",
    "category": "基础质检",
    "scope": "检索片段与当前问题",
    "target": "检索片段与当前问题",
    "engine": "LLMRAGContextRelevancy",
    "severity": "REVIEW",
    "description": "检索片段与当前问题",
    "passCriteria": "相关性达到标准",
    "failCriteria": "无关内容比例或相关性评分不达标",
    "priority": "P0",
    "source": "LLMRAGContextRelevancy",
    "xiamen": "有：RAG上下文相关性（39）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L53",
    "rule_id": "L53",
    "name": "检索上下文精确度",
    "category": "基础质检",
    "scope": "有序检索结果中有用证据的位置与比例",
    "target": "有序检索结果中有用证据的位置与比例",
    "engine": "LLMRAGContextPrecision；按实现提供问题、上下文及参考回答",
    "severity": "REVIEW",
    "description": "有序检索结果中有用证据的位置与比例",
    "passCriteria": "精确度达到标准",
    "failCriteria": "精确度低于标准",
    "priority": "P0",
    "source": "LLMRAGContextPrecision；按实现提供问题、上下文及参考回答",
    "xiamen": "有：RAG上下文精确度（37）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L54",
    "rule_id": "L54",
    "name": "检索上下文召回率",
    "category": "基础质检",
    "scope": "检索内容对参考答案所需事实的覆盖",
    "target": "检索内容对参考答案所需事实的覆盖",
    "engine": "LLMRAGContextRecall；需独立参考答案，不拿待评回答自证",
    "severity": "REVIEW",
    "description": "检索内容对参考答案所需事实的覆盖",
    "passCriteria": "覆盖达到标准",
    "failCriteria": "所需事实覆盖不足",
    "priority": "P0",
    "source": "LLMRAGContextRecall；需独立参考答案，不拿待评回答自证",
    "xiamen": "有：RAG上下文召回率（38）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L55",
    "rule_id": "L55",
    "name": "引用片段起始完整性",
    "category": "基础质检",
    "scope": "实际引用片段的开头是否被截断",
    "target": "实际引用片段的开头是否被截断",
    "engine": "LLMChunkQuality的截断诊断；需按子诊断映射",
    "severity": "REVIEW",
    "description": "实际引用片段的开头是否被截断",
    "passCriteria": "无影响使用的起始截断",
    "failCriteria": "开头文字或公式被截断",
    "priority": "P0",
    "source": "LLMChunkQuality的截断诊断；需按子诊断映射",
    "xiamen": "有：引用块质量评估（6）包含此维度",
    "example": false,
    "enabled": true
  },
  {
    "id": "L56",
    "rule_id": "L56",
    "name": "引用片段头部重复",
    "category": "基础质检",
    "scope": "实际引用片段的开头是否异常重复",
    "target": "实际引用片段的开头是否异常重复",
    "engine": "LLMChunkQuality的重复诊断；输入对象不同于正文重复",
    "severity": "REVIEW",
    "description": "实际引用片段的开头是否异常重复",
    "passCriteria": "无影响使用的头部重复",
    "failCriteria": "出现影响使用的头部重复",
    "priority": "P0",
    "source": "LLMChunkQuality的重复诊断；输入对象不同于正文重复",
    "xiamen": "有：引用块质量评估（6）包含此维度",
    "example": false,
    "enabled": true
  },
  {
    "id": "L57",
    "rule_id": "L57",
    "name": "代码块/列表格式",
    "category": "基础质检",
    "scope": "含代码块或列表的消息格式",
    "target": "含代码块或列表的消息格式",
    "engine": "LLMTextCodeListIssue；代码正确性另设业务规则",
    "severity": "REVIEW",
    "description": "含代码块或列表的消息格式",
    "passCriteria": "结构、缩进或列表组织符合标准",
    "failCriteria": "格式损坏影响理解",
    "priority": "P0",
    "source": "LLMTextCodeListIssue；代码正确性另设业务规则",
    "xiamen": "有：代码块/列表格式问题（51）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L58",
    "rule_id": "L58",
    "name": "公式表示质量",
    "category": "基础质检",
    "scope": "含公式消息中的公式表示",
    "target": "含公式消息中的公式表示",
    "engine": "LLMTextEquation；从消息提取公式并适配输入",
    "severity": "REVIEW",
    "description": "含公式消息中的公式表示",
    "passCriteria": "公式语法与表示完整、可理解",
    "failCriteria": "表示损坏或公式语法异常",
    "priority": "P0",
    "source": "LLMTextEquation；从消息提取公式并适配输入",
    "xiamen": "有：文本公式质量评估（52）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L59",
    "rule_id": "L59",
    "name": "公式重复",
    "category": "基础质检",
    "scope": "消息中的重复公式片段",
    "target": "消息中的重复公式片段",
    "engine": "RuleDocFormulaRepeat",
    "severity": "REVIEW",
    "description": "消息中的重复公式片段",
    "passCriteria": "未达到异常重复条件",
    "failCriteria": "达到异常重复条件",
    "priority": "P0",
    "source": "RuleDocFormulaRepeat",
    "xiamen": "有：公式重复检测（98）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L60",
    "rule_id": "L60",
    "name": "表格表示质量",
    "category": "基础质检",
    "scope": "消息内表格的结构和可理解性",
    "target": "消息内表格的结构和可理解性",
    "engine": "LLMTextTable；按其HTML表格输入适配",
    "severity": "REVIEW",
    "description": "消息内表格的结构和可理解性",
    "passCriteria": "表格结构完整且达到标准",
    "failCriteria": "结构损坏、错乱或不可理解",
    "priority": "P0",
    "source": "LLMTextTable；按其HTML表格输入适配",
    "xiamen": "有：文本表格质量评估（67）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L61",
    "rule_id": "L61",
    "name": "LaTeX特殊标记残留",
    "category": "基础质检",
    "scope": "不应出现LaTeX标记的正文",
    "target": "不应出现LaTeX标记的正文",
    "engine": "RuleLatexSpecialChar；公式教学不直接套用",
    "severity": "REVIEW",
    "description": "不应出现LaTeX标记的正文",
    "passCriteria": "无配置禁止的LaTeX特殊标记",
    "failCriteria": "命中禁止标记",
    "priority": "P0",
    "source": "RuleLatexSpecialChar；公式教学不直接套用",
    "xiamen": "有：LaTeX特殊字符检测（125）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L62",
    "rule_id": "L62",
    "name": "考题/题库内容识别",
    "category": "基础质检",
    "scope": "文本是否属于考题或题库",
    "target": "文本是否属于考题或题库",
    "engine": "LLMTextKaoti；考题内容本身不统一判坏",
    "severity": "REVIEW",
    "description": "文本是否属于考题或题库",
    "passCriteria": "符合模板对考题内容的允许策略",
    "failCriteria": "命中模板禁止的考题内容",
    "priority": "P0",
    "source": "LLMTextKaoti；考题内容本身不统一判坏",
    "xiamen": "有：考题/题库内检测（53）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L63",
    "rule_id": "L63",
    "name": "多语言文本质量",
    "category": "基础质检",
    "scope": "模板指定语言的正文质量",
    "target": "模板指定语言的正文质量",
    "engine": "LLMTextLanguageAr、LLMTextLanguageCs、LLMTextLanguageHu、LLMTextLanguageKo、LLMTextLanguageRu、LLMTextLanguageSr、LLMTextLanguageTh、LLMTextLanguageVi；按语言选择实现",
    "severity": "REVIEW",
    "description": "模板指定语言的正文质量",
    "passCriteria": "相应语言评估达到任务标准",
    "failCriteria": "语言质量未达标",
    "priority": "P0",
    "source": "LLMTextLanguageAr、LLMTextLanguageCs、LLMTextLanguageHu、LLMTextLanguageKo、LLMTextLanguageRu、LLMTextLanguageSr、LLMTextLanguageTh、LLMTextLanguageVi；按语言选择实现",
    "xiamen": "有：阿拉伯语至越南语文本质量（54～61）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L64",
    "rule_id": "L64",
    "name": "多语言来源残留",
    "category": "基础质检",
    "scope": "相应语言的正文中来源说明残留",
    "target": "相应语言的正文中来源说明残留",
    "engine": "RuleHeadWordAr、RuleHeadWordCs、RuleHeadWordHu、RuleHeadWordKo、RuleHeadWordRu、RuleHeadWordSr、RuleHeadWordTh、RuleHeadWordVi",
    "severity": "REVIEW",
    "description": "相应语言的正文中来源说明残留",
    "passCriteria": "无配置禁止的来源残留",
    "failCriteria": "命中禁止残留",
    "priority": "P0",
    "source": "RuleHeadWordAr、RuleHeadWordCs、RuleHeadWordHu、RuleHeadWordKo、RuleHeadWordRu、RuleHeadWordSr、RuleHeadWordTh、RuleHeadWordVi",
    "xiamen": "有：阿拉伯语至越南语尾部来源检测（104～111）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L65",
    "rule_id": "L65",
    "name": "单词数量",
    "category": "基础质检",
    "scope": "适用语言正文的词数",
    "target": "适用语言正文的词数",
    "engine": "RuleWordNumber；中文须校准分词口径",
    "severity": "REVIEW",
    "description": "适用语言正文的词数",
    "passCriteria": "符合所选计数实现及数量阈值",
    "failCriteria": "词数超出配置限制",
    "priority": "P0",
    "source": "RuleWordNumber；中文须校准分词口径",
    "xiamen": "有：单词数量检查（159）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L66",
    "rule_id": "L66",
    "name": "句子数量",
    "category": "基础质检",
    "scope": "正文句子数",
    "target": "正文句子数",
    "engine": "RuleSentenceNumber；明确中文句界",
    "severity": "REVIEW",
    "description": "正文句子数",
    "passCriteria": "符合配置限制",
    "failCriteria": "句子数超出配置限制",
    "priority": "P0",
    "source": "RuleSentenceNumber；明确中文句界",
    "xiamen": "有：句子数量检查（151）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L67",
    "rule_id": "L67",
    "name": "平均词长",
    "category": "基础质检",
    "scope": "正文分词后的平均词长",
    "target": "正文分词后的平均词长",
    "engine": "RuleMeanWordLength",
    "severity": "REVIEW",
    "description": "正文分词后的平均词长",
    "passCriteria": "位于配置区间",
    "failCriteria": "不在配置区间",
    "priority": "P0",
    "source": "RuleMeanWordLength",
    "xiamen": "有：平均词长检查（131）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L68",
    "rule_id": "L68",
    "name": "大写单词占比",
    "category": "基础质检",
    "scope": "正文中的大写词占比",
    "target": "正文中的大写词占比",
    "engine": "RuleCapitalWords；用于有大小写的语言",
    "severity": "REVIEW",
    "description": "正文中的大写词占比",
    "passCriteria": "不超过配置阈值",
    "failCriteria": "超过阈值",
    "priority": "P0",
    "source": "RuleCapitalWords；用于有大小写的语言",
    "xiamen": "有：大写单词占比检查（86）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L69",
    "rule_id": "L69",
    "name": "字母词占比",
    "category": "基础质检",
    "scope": "正文中含字母词项的比例",
    "target": "正文中含字母词项的比例",
    "engine": "RuleAlphaWords；分词及语言需适配",
    "severity": "REVIEW",
    "description": "正文中含字母词项的比例",
    "passCriteria": "符合配置阈值",
    "failCriteria": "不符合阈值",
    "priority": "P0",
    "source": "RuleAlphaWords；分词及语言需适配",
    "xiamen": "未能确认：字段单点比检查（80）描述为列非空比例，与源码不同",
    "example": false,
    "enabled": true
  },
  {
    "id": "L70",
    "rule_id": "L70",
    "name": "停用词占比",
    "category": "基础质检",
    "scope": "指定语言词表中的停用词比例",
    "target": "指定语言词表中的停用词比例",
    "engine": "RuleStopWord",
    "severity": "REVIEW",
    "description": "指定语言词表中的停用词比例",
    "passCriteria": "符合配置范围",
    "failCriteria": "不符合范围",
    "priority": "P0",
    "source": "RuleStopWord",
    "xiamen": "有：停用词占比检查（154）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L71",
    "rule_id": "L71",
    "name": "符号与单词比例",
    "category": "基础质检",
    "scope": "指定符号数与词数之比",
    "target": "指定符号数与词数之比",
    "engine": "RuleSymbolWordRatio",
    "severity": "REVIEW",
    "description": "指定符号数与词数之比",
    "passCriteria": "不超过配置阈值",
    "failCriteria": "超过阈值",
    "priority": "P0",
    "source": "RuleSymbolWordRatio",
    "xiamen": "有：符号与单词比例检查（155）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L72",
    "rule_id": "L72",
    "name": "唯一词占比",
    "category": "基础质检",
    "scope": "不同词项数与总词数之比",
    "target": "不同词项数与总词数之比",
    "engine": "RuleUniqueWords；不替代正文重复定位",
    "severity": "REVIEW",
    "description": "不同词项数与总词数之比",
    "passCriteria": "符合配置阈值",
    "failCriteria": "不符合阈值",
    "priority": "P0",
    "source": "RuleUniqueWords；不替代正文重复定位",
    "xiamen": "有：唯一词占比检查（156）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L73",
    "rule_id": "L73",
    "name": "花括号占比",
    "category": "基础质检",
    "scope": "正文中左右花括号占比",
    "target": "正文中左右花括号占比",
    "engine": "RuleCurlyBracket",
    "severity": "REVIEW",
    "description": "正文中左右花括号占比",
    "passCriteria": "不超过配置阈值",
    "failCriteria": "超过阈值；JSON/代码场景按模板允许",
    "priority": "P0",
    "source": "RuleCurlyBracket",
    "xiamen": "未能确认：低符号占比检查（96）描述不是花括号占比",
    "example": false,
    "enabled": true
  },
  {
    "id": "L74",
    "rule_id": "L74",
    "name": "省略号结尾行占比",
    "category": "基础质检",
    "scope": "以省略号结尾的行/段比例",
    "target": "以省略号结尾的行/段比例",
    "engine": "RuleLineEndWithEllipsis",
    "severity": "REVIEW",
    "description": "以省略号结尾的行/段比例",
    "passCriteria": "不超过配置阈值",
    "failCriteria": "超过阈值",
    "priority": "P0",
    "source": "RuleLineEndWithEllipsis",
    "xiamen": "未能确认：每轮对话长度占比（126）名称与源码含义不同",
    "example": false,
    "enabled": true
  },
  {
    "id": "L75",
    "rule_id": "L75",
    "name": "终止标点结尾占比",
    "category": "基础质检",
    "scope": "以句末标点结束的行/段比例",
    "target": "以句末标点结束的行/段比例",
    "engine": "RuleLineEndWithTerminal；配置中文标点",
    "severity": "REVIEW",
    "description": "以句末标点结束的行/段比例",
    "passCriteria": "达到配置下限",
    "failCriteria": "低于下限",
    "priority": "P0",
    "source": "RuleLineEndWithTerminal；配置中文标点",
    "xiamen": "有：终止标点结尾占比（127）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L76",
    "rule_id": "L76",
    "name": "段落标点缺失",
    "category": "基础质检",
    "scope": "段落中的标点数量/缺失情况",
    "target": "段落中的标点数量/缺失情况",
    "engine": "RuleNoPunc",
    "severity": "REVIEW",
    "description": "段落中的标点数量/缺失情况",
    "passCriteria": "满足所选标点要求",
    "failCriteria": "达到标点缺失的异常条件",
    "priority": "P0",
    "source": "RuleNoPunc",
    "xiamen": "有：段落标点缺失检测（133）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L77",
    "rule_id": "L77",
    "name": "冒号结尾",
    "category": "基础质检",
    "scope": "疑似以冒号截断的文本",
    "target": "疑似以冒号截断的文本",
    "engine": "RuleColonEnd；短对话提示语可合法以冒号结束",
    "severity": "REVIEW",
    "description": "疑似以冒号截断的文本",
    "passCriteria": "未出现模板禁止的冒号结尾",
    "failCriteria": "出现禁止的冒号结尾",
    "priority": "P0",
    "source": "RuleColonEnd；短对话提示语可合法以冒号结束",
    "xiamen": "有：冒号结尾检测（89）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L78",
    "rule_id": "L78",
    "name": "项目符号开头行占比",
    "category": "基础质检",
    "scope": "以项目符号开头的行比例",
    "target": "以项目符号开头的行比例",
    "engine": "RuleLineStartWithBulletpoint",
    "severity": "REVIEW",
    "description": "以项目符号开头的行比例",
    "passCriteria": "不超过配置阈值",
    "failCriteria": "超过阈值；列表型回复按模板允许",
    "priority": "P0",
    "source": "RuleLineStartWithBulletpoint",
    "xiamen": "有：项目符号开头行占比（129）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L79",
    "rule_id": "L79",
    "name": "JavaScript文本占比",
    "category": "基础质检",
    "scope": "正文中JavaScript相关行/片段的统计",
    "target": "正文中JavaScript相关行/片段的统计",
    "engine": "RuleLineJavascriptCount",
    "severity": "REVIEW",
    "description": "正文中JavaScript相关行/片段的统计",
    "passCriteria": "不超过配置阈值",
    "failCriteria": "超过阈值；编程场景按模板允许",
    "priority": "P0",
    "source": "RuleLineJavascriptCount",
    "xiamen": "有：JavaScript文本占比（128）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L80",
    "rule_id": "L80",
    "name": "异常页码/索引残留",
    "category": "基础质检",
    "scope": "从文档来源引入正文的页码或索引碎片",
    "target": "从文档来源引入正文的页码或索引碎片",
    "engine": "RuleAbnormalNumber",
    "severity": "REVIEW",
    "description": "从文档来源引入正文的页码或索引碎片",
    "passCriteria": "无达到规则条件的异常残留",
    "failCriteria": "存在异常残留",
    "priority": "P0",
    "source": "RuleAbnormalNumber",
    "xiamen": "有：异常页码/索引号检测（79）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L81",
    "rule_id": "L81",
    "name": "字典值一致性",
    "category": "基础质检",
    "scope": "两个待比对字典的键和值；如事件事实与从消息提取的事实",
    "target": "两个待比对字典的键和值；如事件事实与从消息提取的事实",
    "engine": "RuleDictConsistency；适配为metadata/context两个字典；事实提取需平台实现",
    "severity": "REVIEW",
    "description": "两个待比对字典的键和值；如事件事实与从消息提取的事实",
    "passCriteria": "按配置映射后值一致",
    "failCriteria": "映射后值不一致",
    "priority": "P0",
    "source": "RuleDictConsistency；适配为metadata/context两个字典；事实提取需平台实现",
    "xiamen": "有：字典一致性校验（97）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L82",
    "rule_id": "L82",
    "name": "自定义模式匹配",
    "category": "场景质检",
    "scope": "用户指定的禁止文本模式",
    "target": "用户指定的禁止文本模式",
    "engine": "RulePatternSearch；允许模式需另定义判定方向",
    "severity": "REVIEW",
    "description": "用户指定的禁止文本模式",
    "passCriteria": "未匹配禁止模式",
    "failCriteria": "匹配禁止模式",
    "priority": "P0",
    "source": "RulePatternSearch；允许模式需另定义判定方向",
    "xiamen": "有：自定义模式匹配（135）",
    "example": false,
    "enabled": true
  },
  {
    "id": "L01",
    "rule_id": "L01",
    "name": "会话消息结构",
    "category": "基础质检",
    "scope": "样本消息序列",
    "target": "样本消息序列",
    "engine": "P1 · 原型messages要求；不等同于Dingo SFT格式",
    "severity": "REVIEW",
    "description": "样本消息序列",
    "passCriteria": "为消息数组，消息数量满足模板及任务标准",
    "failCriteria": "缺失、结构不符或消息数量不足",
    "priority": "P1",
    "source": "P1 · 原型messages要求；不等同于Dingo SFT格式",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "L03",
    "rule_id": "L03",
    "name": "角色合法",
    "category": "基础质检",
    "scope": "各消息角色",
    "target": "各消息角色",
    "engine": "P1 · 对话角色协议",
    "severity": "REVIEW",
    "description": "各消息角色",
    "passCriteria": "属于模板允许的角色集合",
    "failCriteria": "角色缺失或不在允许集合内",
    "priority": "P1",
    "source": "P1 · 对话角色协议",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "L04",
    "rule_id": "L04",
    "name": "消息内容类型",
    "category": "基础质检",
    "scope": "消息正文及内容块",
    "target": "消息正文及内容块",
    "engine": "P1 · 原型消息内容要求；Dingo空文本规则不负责类型检查",
    "severity": "REVIEW",
    "description": "消息正文及内容块",
    "passCriteria": "符合模板规定的字符串/内容块类型和结构",
    "failCriteria": "类型或内容块结构不符；文本非空单独见L10",
    "priority": "P1",
    "source": "P1 · 原型消息内容要求；Dingo空文本规则不负责类型检查",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "L05",
    "rule_id": "L05",
    "name": "消息顺序",
    "category": "基础质检",
    "scope": "消息角色及轮次顺序",
    "target": "消息角色及轮次顺序",
    "engine": "P1 · 对话顺序规则",
    "severity": "REVIEW",
    "description": "消息角色及轮次顺序",
    "passCriteria": "满足模板规定的起始、交替及结束要求",
    "failCriteria": "违反所选协议，不将固定交替要求套用到所有场景",
    "priority": "P1",
    "source": "P1 · 对话顺序规则",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "L06",
    "rule_id": "L06",
    "name": "跨轮实体一致性",
    "category": "场景质检",
    "scope": "不同消息中同一人物、订单或其他实体",
    "target": "不同消息中同一人物、订单或其他实体",
    "engine": "P1 · 原跨轮一致性需求；不执行脱敏检测或替换",
    "severity": "REVIEW",
    "description": "不同消息中同一人物、订单或其他实体",
    "passCriteria": "在无明确业务变化的情况下，实体身份和关键属性前后一致",
    "failCriteria": "同一实体出现无解释的身份、编号或属性冲突",
    "priority": "P1",
    "source": "P1 · 原跨轮一致性需求；不执行脱敏检测或替换",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  },
  {
    "id": "L09",
    "rule_id": "L09",
    "name": "工具调用协议",
    "category": "场景质检",
    "scope": "消息中的工具调用内容",
    "target": "消息中的工具调用内容",
    "engine": "P1 · 原工具调用边界要求",
    "severity": "REVIEW",
    "description": "消息中的工具调用内容",
    "passCriteria": "符合模板选定协议；未启用工具时不出现工具调用，启用时结构符合协议",
    "failCriteria": "出现未允许的调用或调用结构违反所选协议",
    "priority": "P1",
    "source": "P1 · 原工具调用边界要求",
    "xiamen": "详见02文档",
    "example": false,
    "enabled": true
  }
];
export const DEFAULT_CONVERSATION_RULE_IDS = CONVERSATION_QUALITY_CATALOG.filter(r=>!r.example).map(r=>r.id);
export const LEGACY_CONVERSATION_RULE_MAP = {
  DINGO_FAITHFULNESS:'L34', DINGO_ANSWER_RELEVANCY:'L07', DINGO_HONEST:'L33',
  DINGO_HELPFUL:'L32', DINGO_HARMLESS:'L30', DINGO_TASK_DIFFICULTY:'L38',
  DINGO_UNSAFE_WORDS:'L27', SCENE_LABEL_COVERAGE:'L08'
};
export function conversationRuleCategory(rule) {
  if (rule.evaluator==='label_coverage' || /LABEL.*COVERAGE|COVERAGE.*LABEL/.test(rule.rule_id||rule.id||'')) return '标签分类';
  if (CONVERSATION_QUALITY_CATEGORIES.includes(rule.category)) return rule.category;
  if (/PRIVACY|PII/.test(rule.rule_id||rule.id||'')) return '隐私质检';
  return '场景质检';
}
export function conversationCatalogRules(quality = {}) {
  const selected = new Set(quality.selected_rule_ids ?? DEFAULT_CONVERSATION_RULE_IDS);
  return CONVERSATION_QUALITY_CATALOG.map(rule => ({...rule, enabled:selected.has(rule.id)}));
}
