import React,{useEffect,useState} from 'react';
import {Button,Checkbox,Collapse,Form,Input,Modal,Select,Space,Table,Typography} from 'antd';
import {modelParametersError} from './ModelConfigField.jsx';
export default function DocumentAugmentationScheme({form,presets}){
 const values=Form.useWatch([],{form,preserve:true})||form.getFieldsValue(true),[editing,setEditing]=useState(null),[editor]=Form.useForm();
 const images=values.documentImageMethods||[],semantic=values.documentSemanticRules||[],custom=values.documentSemanticCustomRules||[],background=values.documentBackgroundMethods||[],customBg=values.documentBackgroundCustomRules||[];
 useEffect(()=>{const types=[...(images.length?['图像增强']:[]),...(semantic.length+custom.length?['语义增强']:[]),...(background.length+customBg.length?['背景增强']:[])];if(JSON.stringify(types)!==JSON.stringify(form.getFieldValue('documentEnhancementTypes')))form.setFieldValue('documentEnhancementTypes',types);},[JSON.stringify([images,semantic,custom,background,customBg])]);
 useEffect(()=>{if(images.includes('旋转 / 透视 / 亮度变化'))form.setFieldValue('documentImageMethods',[...new Set(images.flatMap(v=>v==='旋转 / 透视 / 亮度变化'?['旋转','透视','亮度变化']:[v]).filter(v=>v!=='标注同步'))]);for(const [name,prefix] of [['documentSemanticCustomRules','documentSemanticCustom'],['documentBackgroundCustomRules','documentBackgroundCustom']])if(form.getFieldValue(name)==null&&form.getFieldValue(prefix+'Enabled'))form.setFieldValue(name,[{name:form.getFieldValue(prefix+'Name'),prompt:form.getFieldValue(prefix+'Prompt')}]);},[]);
 const imageOptions=['模糊','噪声','压缩失真','旋转','透视','亮度变化','折痕','扫描 / 复印','污渍'];
 const imageDescriptions={
  '模糊':'模拟失焦或拍摄抖动，使文字与边缘不同程度变模糊。',
  '噪声':'添加颗粒或随机噪点，模拟低光照与设备采集干扰。',
  '压缩失真':'模拟有损压缩产生的块状纹理和边缘失真。',
  '旋转':'整体旋转页面，模拟文档放置或拍摄时的倾斜。',
  '透视':'改变页面四角位置，模拟斜拍造成的形变。',
  '亮度变化':'调整图像明暗，模拟不同光照与曝光条件。',
  '折痕':'添加纸张折叠产生的线条、阴影和局部形变。',
  '扫描 / 复印':'模拟扫描或复印后的对比度变化、底灰与细节损失。',
  '污渍':'添加污点或水渍，模拟纸张表面污染和局部遮挡。',
 };
 useEffect(()=>{if(images.includes('文档退化'))form.setFieldValue('documentImageMethods',[...new Set(images.flatMap(v=>v==='文档退化'?['模糊','噪声','压缩失真']:[v]))]);},[JSON.stringify(images)]);
 const edit=(field,index)=>{setEditing({field,index});editor.setFieldsValue(index==null?{name:'',prompt:''}:form.getFieldValue(field)[index]);};
 const customList=(field,items)=><><Space style={{display:'flex',justifyContent:'space-between',margin:'16px 0'}}><Typography.Text strong>自定义规则</Typography.Text><Button onClick={()=>edit(field,null)}>添加规则</Button></Space>{items.length>0&&<Table size="small" pagination={false} dataSource={items.map((r,i)=>({...r,key:i}))} tableLayout="fixed" scroll={{x:620}} columns={[{title:'规则名称',dataIndex:'name',width:160},{title:'增强 Prompt',dataIndex:'prompt',render:value=><Typography.Paragraph style={{margin:0,overflowWrap:'anywhere'}} ellipsis={{rows:2,tooltip:value}}>{value}</Typography.Paragraph>},{title:'操作',width:150,render:(_,r)=><Space size={4} style={{whiteSpace:'nowrap'}}><Button style={{whiteSpace:'nowrap'}} type="link" onClick={()=>edit(field,r.key)}>编辑</Button><Button style={{whiteSpace:'nowrap'}} type="link" danger onClick={()=>form.setFieldValue(field,items.filter((_,i)=>i!==r.key))}>删除</Button></Space>}]}/>}</>;
 const model=(name,label,options)=><div style={{marginTop:20}}><Form.Item name={name} label={label} initialValue={options[0]} rules={[{required:true}]}><Select placeholder={`请选择${label}`} options={options.map(value=>({value,label:value}))}/></Form.Item><Collapse ghost items={[{key:'parameters',label:'高级参数',children:<Form.Item name={name.replace(/Model$/,'')+'Parameters'} label="模型参数" rules={[{validator:(_,value)=>{const error=modelParametersError(value,true);return error?Promise.reject(new Error(error)):Promise.resolve();}}]}><Input.TextArea rows={3} placeholder={'{"temperature":0.7}'} onChange={()=>form.setFieldValue(name.replace(/Model$/,'')+'ParametersEnabled',true)}/></Form.Item>}]}/></div>;
 const title=(name,items)=><Space wrap><Typography.Text strong>{name}</Typography.Text><Typography.Text type="secondary">{items.length?`已选 ${items.length} 项`:'未配置'}</Typography.Text></Space>;
 return <>{['documentEnhancementTypes','documentSemanticRules','documentSemanticCustomRules','documentBackgroundCustomRules'].map(name=><Form.Item key={name} name={name} hidden><Input/></Form.Item>)}<Collapse defaultActiveKey={['image']} items={[
 {key:'image',label:title('图像增强',images),forceRender:true,children:<><Form.Item name="documentImageMethods" initialValue={['模糊']} hidden><Input/></Form.Item><Table size="small" rowKey="name" pagination={false} dataSource={imageOptions.map(name=>({name}))} columns={[{title:'启用',width:64,render:(_,r)=><Checkbox aria-label={'启用'+r.name} checked={images.includes(r.name)} onChange={e=>form.setFieldValue('documentImageMethods',e.target.checked?[...images,r.name]:images.filter(v=>v!==r.name))}/>},{title:'增强方式',dataIndex:'name',width:140},{title:'说明',render:(_,r)=><Typography.Text type="secondary">{imageDescriptions[r.name]}</Typography.Text>},{title:'强度',width:180,render:(_,r)=><Form.Item name={['documentImageIntensities',r.name]} initialValue="轻度" style={{margin:0}}><Select placeholder="请选择强度" aria-label={r.name+'强度'} disabled={!images.includes(r.name)} options={['轻度','中等','重度'].map(value=>({value,label:value}))}/></Form.Item>} ]}/></>},
 {key:'semantic',label:title('语义增强',[...semantic.map(id=>presets.find(r=>r.id===id)?.name||id),...custom.map(r=>r.name)]),forceRender:true,children:<><Table size="small" pagination={false} rowKey="id" dataSource={presets} rowSelection={{selectedRowKeys:semantic,onChange:keys=>form.setFieldValue('documentSemanticRules',keys)}} columns={[{title:'预置规则',dataIndex:'name'},{title:'说明',render:(_,r)=><Typography.Text ellipsis={{tooltip:r.prompt}} style={{maxWidth:280}}>{r.prompt}</Typography.Text>},{title:'操作',render:(_,r)=><Button type="link" onClick={()=>Modal.info({title:r.name,content:r.prompt})}>查看详情</Button>}]}/>{customList('documentSemanticCustomRules',custom)}{semantic.length+custom.length>0&&model('semanticEnhancementModel','语义增强模型',['Qwen3-14B','Qwen3-VL-8B-Instruct','DeepSeek-V3.1'])}</>},
 {key:'background',label:title('背景增强',[...background,...customBg.map(r=>r.name)]),forceRender:true,children:<><Form.Item name="documentBackgroundMethods"><Checkbox.Group options={['桌面拍摄背景','文件夹衬底背景','扫描边缘背景']}/></Form.Item>{customList('documentBackgroundCustomRules',customBg)}{background.length+customBg.length>0&&model('backgroundEnhancementModel','图像生成模型',['Doubao-Seedream-4.0','Qwen-Image'])}</>}
 ]}/><Typography.Paragraph type="secondary" style={{marginTop:12}}>语义规则全部执行，图像效果随机组合，背景方式每次任选一种。</Typography.Paragraph><Modal title="自定义增强规则" open={!!editing} onCancel={()=>setEditing(null)} onOk={async()=>{const value=await editor.validateFields();const items=[...(form.getFieldValue(editing.field)||[])];if(editing.index==null)items.push(value);else items[editing.index]=value;form.setFieldValue(editing.field,items);setEditing(null);}}><Form form={editor} layout="vertical"><Form.Item name="name" label="规则名称" rules={[{required:true,whitespace:true}]}><Input placeholder="请输入规则名称"/></Form.Item><Form.Item name="prompt" label="增强 Prompt" rules={[{required:true,whitespace:true}]}><Input.TextArea placeholder="描述增强 Prompt，说明目标、约束和输出要求" rows={5}/></Form.Item></Form></Modal></>;
}
