export const DOCUMENT_BASE_QUALITY_RULES = [
  ['DINGO-IMAGE-DATA-FORMAT','文件格式合法性','样本','Dingo · RuleImageDataFormat','BLOCK','检查文件扩展名、实际编码与允许格式是否一致。'],
  ['DINGO-IMAGE-VALID','文件/记录可读取性','样本','Dingo · RuleImageValid','BLOCK','检查图像是否损坏、空文件或无法解码。'],
  ['DINGO-IMAGE-WHITE-BLACK','纯白/纯黑图检测','样本','Dingo · RuleImageValid','BLOCK','识别无有效内容的纯白图、纯黑图。'],
  ['DINGO-IMAGE-SIZE','图像尺寸合法性','样本','Dingo · RuleImageSizeValid','BLOCK','检查宽高、长宽比及最小分辨率。'],
  ['BASE-FILE-SIZE','文件大小合法性','样本','系统规则','BLOCK','检查文件体积是否位于模板允许范围。'],
  ['BASE-COLOR-MODE','颜色模式合法性','样本','系统规则','REVIEW','检查灰度、RGB、RGBA 等颜色模式是否符合配置。'],
  ['BASE-FRAME-COUNT','页数/帧数合法性','样本','系统规则','BLOCK','检查单页图、多页 TIFF 等页数或帧数约束。'],
  ['BASE-ORIENTATION-METADATA','方向元数据合法性','样本','系统规则','REVIEW','检查 EXIF 方向与实际像素方向是否一致。'],
  ['BASE-ALPHA-CHANNEL','透明通道合法性','样本','系统规则','REVIEW','检查透明区域是否造成文档内容缺失。'],
  ['DINGO-IMAGE-REPEAT','重复图像检测','数据集','Dingo · RuleImageRepeat','BLOCK','检测完全重复或近似重复的图像样本。'],
  ['BASE-UNIQUE-ID','唯一标识合法性','数据集','系统规则','BLOCK','检查样本 ID 非空、格式合法且全局唯一。'],

  ['DINGO-IMAGE-QUALITY','清晰度/模糊度','样本 + 区域','Dingo · RuleImageQuality','BLOCK','通过清晰度特征识别失焦、抖动和文字边缘模糊。'],
  ['BASE-BRIGHTNESS','亮度合法性','样本 + 区域','系统规则','REVIEW','检查整图及关键区域平均亮度是否位于配置区间。'],
  ['BASE-EXPOSURE-RATIO','过曝/欠曝区域占比','样本 + 区域','系统规则','REVIEW','统计极亮、极暗像素在整图和关键区域中的占比。'],
  ['BASE-CONTRAST','对比度合法性','样本 + 区域','系统规则','REVIEW','检查文字与背景对比度是否满足阅读及 OCR 要求。'],
  ['BASE-SHADOW','阴影遮盖率','区域','系统视觉算法','REVIEW','检查阴影是否覆盖关键字段并造成识别损失。'],
  ['BASE-NOISE','图像噪声强度','样本','系统视觉算法','REVIEW','估算噪声水平，检查其是否破坏文字结构。'],
  ['BASE-COMPRESSION','压缩伪影强度','样本','系统视觉算法','REVIEW','检测 JPEG 块效应、振铃等压缩伪影。'],
  ['BASE-COLOR-CAST','色偏异常','样本 + 区域','系统视觉算法','REVIEW','检测整体或局部颜色偏移。'],
  ['BASE-STRIPE-MOIRE','条纹/摩尔纹检测','样本','系统视觉算法','REVIEW','检测扫描条纹、屏摄摩尔纹等结构性干扰。'],
  ['BASE-DOCUMENT-COVERAGE','文档主体覆盖率','样本','系统视觉算法','REVIEW','检查文档主体占画布面积比例及异常留白。'],
  ['BASE-DOCUMENT-EDGE','文档边缘完整性','样本','系统视觉算法','BLOCK','检查文档四边是否完整可见。'],
  ['BASE-KEY-CROP','关键内容裁切检测','区域','系统视觉算法','BLOCK','检查关键表格、字段和印章是否被裁断。'],
  ['BASE-ROTATION','旋转角度合法性','样本','系统视觉算法','REVIEW','检查页面旋转角度是否在模板允许范围。'],
  ['BASE-PERSPECTIVE','透视形变合法性','样本','系统视觉算法','REVIEW','检查透视扰动是否在配置范围且未破坏字段真值。'],

  ['DINGO-LABEL-OVERLAP','标注框重叠','标注','Dingo · RuleImageLabelOverlap','BLOCK','检测不符合模板嵌套关系的 bbox/polygon 重叠。'],
  ['BASE-LABEL-BOUNDS','标注坐标越界','标注','系统规则','BLOCK','检查 bbox/polygon 坐标有效且位于画布内。'],
  ['BASE-LABEL-DEGENERATE','退化标注框','标注','系统规则','BLOCK','检查标注框宽高、面积以及多边形顶点有效性。'],
  ['BASE-LABEL-CATEGORY','标注类别合法性','标注','系统规则','BLOCK','检查标签值属于模板定义的类别集合。'],
  ['BASE-LABEL-ID','标注 ID 唯一性','标注','系统规则','BLOCK','检查标注对象 ID 非空且唯一。'],
  ['BASE-LABEL-ASSET-BINDING','标注与图像绑定完整性','记录','系统规则','BLOCK','检查每条标注都能关联到存在的图像样本。'],
  ['BASE-LABEL-COVERAGE','标注覆盖完整性','样本 + 标注','系统规则','BLOCK','检查应标区域、字段及版面对象是否存在对应标注。'],
  ['BASE-LABEL-TEXT-MATCH','标注文本与区域一致性','区域','系统规则 + OCR','REVIEW','检查标注文本与对应图像区域 OCR 结果是否一致。'],
  ['DINGO-LAYOUT-QUALITY','版面检测质量','样本 + 标注','Dingo · VLMLayoutQuality','REVIEW','评估版面区域类别、位置和阅读顺序是否合理。'],
  ['BASE-READING-ORDER','阅读顺序合法性','样本 + 标注','系统规则','REVIEW','检查标题、段落、表格等对象阅读顺序。'],
  ['BASE-TABLE-STRUCTURE','表格结构完整性','表格','系统规则','BLOCK','检查行列、合并单元格及边界关系完整。'],
  ['BASE-LAYOUT-TEMPLATE','版面与模板一致性','样本','系统规则','REVIEW','检查主要版面对象与模板约束的一致性。'],
  ['BASE-ASSET-OCCLUSION','图案/印章遮挡','区域','系统规则','REVIEW','检查图案、印章是否异常遮挡关键字段。'],

  ['BASE-FIELD-ID','字段 ID 合法性','字段','系统规则','BLOCK','检查动态字段 ID 非空、唯一并符合命名规则。'],
  ['BASE-FIELD-REQUIRED','必填字段值完整性','字段','系统规则','BLOCK','逐项检查模板必填字段是否生成非空值。'],
  ['BASE-FIELD-TYPE','字段数据类型合法性','字段','系统规则','BLOCK','检查字段值与 text、date、amount、enum 等声明类型一致。'],
  ['BASE-FIELD-FORMAT','字段格式合法性','字段','系统规则','BLOCK','按字段独立格式规则检查日期、金额、代码等值。'],
  ['BASE-FIELD-ENUM','枚举值合法性','字段','系统规则','BLOCK','检查枚举字段值属于配置候选集。'],
  ['BASE-FIELD-GENERATOR','字段生成规则完整性','字段','系统规则','BLOCK','检查生成器、字典、Prompt 或表达式配置完整。'],
  ['BASE-FIELD-BINDING','字段与图层绑定完整性','字段 + 图层','系统规则','BLOCK','检查动态字段与文字框、单元格的绑定关系。'],
  ['BASE-FIELD-VALUE-UNIQUE','业务唯一字段重复','数据集 + 字段','系统规则','BLOCK','检查配置为唯一的单号、流水号等业务字段。'],
  ['BASE-CROSS-FIELD','跨字段约束合法性','记录','系统规则','BLOCK','检查金额、日期、数量及主体等字段之间的确定性约束。'],
  ['BASE-TEXT-OVERFLOW','文字溢出检测','字段 + 区域','系统渲染检测','BLOCK','检查生成文字是否超出绑定框或发生裁切。'],
  ['BASE-MIN-FONT-SIZE','最小字号合法性','字段 + 区域','系统渲染检测','REVIEW','检查缩放或自适应后的实际字号。'],
  ['BASE-TEXT-ALIGNMENT','文字对齐合法性','字段 + 区域','系统渲染检测','REVIEW','检查文字在单元格或文本框内的对齐方式。'],
  ['BASE-GLYPH-MISSING','缺字/乱码检测','字段 + 区域','系统渲染检测','BLOCK','检查字体缺失、方框字和编码乱码。'],
  ['BASE-ASSET-REFERENCE','图案素材引用有效性','图案','系统规则','BLOCK','检查印章、图标、条码等素材存在且可读取。'],
  ['BASE-CODE-DECODABLE','条码/二维码可解码性','区域','系统解码器','BLOCK','检查生成码可解码且内容符合安全前缀要求。'],
  ['BASE-RENDER-SIZE','成品输出尺寸合法性','样本','系统规则','BLOCK','检查试运行成品尺寸与渲染配置一致。'],
  ['BASE-GROUND-TRUTH','成品与字段真值一致性','字段 + 区域','系统规则 + OCR','BLOCK','检查渲染成品中的字段内容与结构化真值一致。'],

  ['DINGO-TEXT-SIMILARITY','OCR 文本相似度','样本 + 字段','Dingo · RuleImageTextSimilarity','BLOCK','比较 OCR 识别文本与字段真值的相似度。'],
  ['DINGO-IMAGE-RELEVANT','图文相关性','样本 + 文本','Dingo · VLMImageRelevant','REVIEW','判断文档图像与配套文本或描述是否相关。'],
  ['DINGO-DOCUMENT-PARSING','原图与 Markdown 解析质量','样本','Dingo · VLMDocumentParsing','REVIEW','比较原始文档图像与 Markdown 解析结果的内容、结构和阅读顺序。'],
  ['DINGO-MINERU-QUALITY','Markdown 解析质量','样本','Dingo · LLMMinerURecognizeQuality','REVIEW','评估文档转 Markdown 后的内容和结构质量。'],
  ['DINGO-OCR-TRAIN','OCR 训练样本逐框评估','样本 + 标注','Dingo · VLMDocumentParsingOCRTrain','BLOCK','逐框检查 OCR 标注、识别内容和位置关系。'],
  ['BASE-OCR-COVERAGE','OCR 文本覆盖率','样本 + 字段','系统 OCR','BLOCK','检查应识别字段被 OCR 结果覆盖的比例。'],
  ['BASE-OCR-CONFIDENCE','OCR 置信度合法性','样本 + 区域','系统 OCR','REVIEW','检查整体及关键区域 OCR 置信度。'],
  ['BASE-OCR-CER','OCR 字符错误率','样本 + 字段','系统 OCR','BLOCK','以字段真值计算 OCR 字符错误率。'],
];

export const DOCUMENT_PRIVACY_QUALITY_RULES = [
  ['DINGO-PII','标准 PII','整图 OCR + 每个字段','Dingo · RulePIIDetection','BLOCK','检测手机号、身份证、邮箱、信用卡、护照、SSN 和 IPv4。'],
  ['FIXED-PRIVACY-PERSON','个人身份隐私','整图 OCR + 每个字段','系统规则 / NER','BLOCK','检查真实姓名及本地个人身份信息。'],
  ['FIXED-PRIVACY-CONTACT','联系与位置隐私','整图 OCR + 每个字段','系统规则 / NER','BLOCK','检查详细地址、邮箱、电话、车牌等联系与位置信息。'],
  ['FIXED-PRIVACY-BUSINESS','业务标识隐私','整图 OCR + 每个字段','业务字典 + 正则','BLOCK','检查真实运单号、客户编号及企业内部账号。'],
  ['FIXED-PRIVACY-CREDENTIAL','账号与密钥安全','整图 OCR + 每个字段','凭据扫描','BLOCK','检查 API Key、Token、Cookie 和密码。'],
  ['FIXED-PRIVACY-RESIDUAL','成品隐私残留复检','最终成品图','OCR + Dingo + 系统规则','BLOCK','对脱敏后的最终图像重新 OCR，确认敏感信息残留数为 0。'],
];

export const DOCUMENT_SCENE_QUALITY_RULES=[
    {rule_id:'SCENE-LAYOUT-FIELD',name:'版面与字段绑定一致性',target:'两者',mode:'semantic',prompt:'判断字段位置、标签、字段值与绑定关系是否符合整张文档的版面语义。',positive_example:'字段值紧邻对应标签，阅读顺序清晰。',negative_example:'字段值与标签错位或绑定到错误区域。',handling:'REVIEW',enabled:true},
    {rule_id:'SCENE-CROSS-FIELD',name:'跨字段业务一致性',target:'字段内容',mode:'semantic',prompt:'判断日期、主体、地点、数量、金额及代码等关联字段是否符合当前业务单据约束。',positive_example:'关联字段逻辑一致且可共同成立。',negative_example:'日期倒置、金额关系冲突或主体不一致。',handling:'BLOCK',enabled:true},
    {rule_id:'SCENE-BUSINESS-SEMANTIC',name:'业务内容语义合理性',target:'字段内容',mode:'semantic',prompt:'判断生成字段的业务含义、上下文和组合关系是否符合该类文档的真实填写逻辑。',positive_example:'内容自然、完整且符合单据用途。',negative_example:'内容虽格式正确但业务含义矛盾。',handling:'REVIEW',enabled:true},
    {rule_id:'SCENE-VLM-LAYOUT',name:'整体版面视觉自然度',target:'版面结构',mode:'vlm',prompt:'直接观察成品图像，判断页面层级、留白、对齐、表格线、字号和各区域组合是否符合该类单据的真实视觉习惯。',positive_example:'版面结构完整、对齐自然、阅读顺序清楚。',negative_example:'字段漂移、区域错位、异常留白或视觉层级混乱。',handling:'REVIEW',enabled:true},
    {rule_id:'SCENE-VLM-IMAGE-FIELD',name:'图像与字段语义一致性',target:'两者',mode:'vlm',prompt:'结合成品图像和结构化字段真值，判断文字值是否出现在正确标签、表格单元格和业务区域中。',positive_example:'字段值与相邻标签、区域和结构化真值一致。',negative_example:'图中文字与字段真值不一致，或字段出现在错误区域。',handling:'BLOCK',enabled:true},
    {rule_id:'SCENE-VLM-OCCLUSION',name:'关键内容遮挡与裁切复核',target:'版面结构',mode:'vlm',prompt:'观察成品图，检查印章、图案、水印、背景、边缘裁切是否影响标题、关键字段、表格和机器码阅读。',positive_example:'图案与水印不遮挡关键字段，页面边缘完整。',negative_example:'印章覆盖字段值，水印干扰 OCR，或关键区域被裁断。',handling:'BLOCK',enabled:true},
  ];

