import React,{useMemo} from 'react';
import {Button,Col,Flex,Row,Space,Statistic,Tooltip,Typography} from 'antd';
import {overallReportMetrics,isDistribution} from './qualityResults';
import {regularQualityReport} from './qualityScope';
import {qualityExecutionMetadata} from './taskExecution';
export default function TaskBasisSummary({report,template,rules=[],quality,onOpen}){
 const metrics=useMemo(()=>overallReportMetrics(regularQualityReport(report?.sampleExecution?.execution&&report.mock?{...report,...qualityExecutionMetadata(report.sampleExecution)}:report)),[report]);
 return <div style={{background:'var(--color-bg-layout, #f5f7fa)',borderRadius:8,padding:20,marginTop:12}}>
 <Flex justify="space-between" align="center" wrap gap={8} style={{marginBottom:16}}><Typography.Text strong>{quality?'质检依据':'质检报告摘要'}</Typography.Text><Button type="link" style={{paddingInline:0,height:'auto',whiteSpace:'nowrap'}} onClick={()=>onOpen(quality?'rules':'report')}>{quality?'查看模板规则':'查看完整报告'} →</Button></Flex>
 {quality?<Flex wrap gap={32} style={{lineHeight:'24px'}}><Space size={8}><Typography.Text type="secondary">启用质量规则</Typography.Text><Typography.Text strong>{rules.filter(r=>!isDistribution(r)).length}</Typography.Text><Typography.Text type="secondary">项</Typography.Text></Space><Space size={8}><Typography.Text type="secondary">标签规则</Typography.Text><Typography.Text strong>{rules.filter(isDistribution).length}</Typography.Text><Typography.Text type="secondary">项</Typography.Text></Space></Flex>:<Row gutter={[16,12]}><Col xs={24} sm={8}><Statistic title="整体质量分" value={metrics.overallScore==null?'—':(metrics.overallScore*100).toFixed(1)} suffix={metrics.overallScore==null?null:'分'}/></Col><Col xs={24} sm={8}><Statistic title={<Tooltip title="通过与不通过的结果数 ÷ 通过、不通过与无法判定的结果数；按样本×规则统计。">有效判定覆盖率 ⓘ</Tooltip>} value={metrics.judgmentCoverage==null?'—':(metrics.judgmentCoverage*100).toFixed(1)+'%'}/></Col><Col xs={24} sm={8}><Typography.Text type="secondary">{report?.executionRange==='sample'?'抽样检查':'全量检查'}</Typography.Text><div style={{marginTop:8}}>{Number(report?.checkedSampleCount||0).toLocaleString()} / {Number(report?.sampleCount||0).toLocaleString()} 条</div></Col></Row>}
 <Flex wrap gap={8} align="baseline" style={{marginTop:12,lineHeight:'24px'}}><Typography.Text type="secondary" style={{flexShrink:0}}>依据模板</Typography.Text><Typography.Text style={{overflowWrap:'anywhere'}}>{template?.name||report?.templateId||'—'}</Typography.Text>{!quality&&<Button type="link" size="small" onClick={()=>onOpen('rules')}>查看模板规则 →</Button>}</Flex></div>;
}
