import React,{useState,useEffect} from 'react';
import {Button,Checkbox,Collapse,Form,Input,Modal,Select,Space,Table,Typography} from 'antd';
import {modelParametersError} from './ModelConfigField.jsx';
export default function TextAugmentationScheme({form,groups}){
 const values=Form.useWatch([],{form,preserve:true})||form.getFieldsValue(true),[editing,setEditing]=useState(null),[editor]=Form.useForm();
 useEffect(()=>{for(const g of groups){if(form.getFieldValue(g.custom)==null&&form.getFieldValue(g.legacy+'Enabled'))form.setFieldValue(g.custom,[{name:form.getFieldValue(g.legacy+'Name'),prompt:form.getFieldValue(g.legacy+'Prompt')}]);}},[]);
 const open=(g,index)=>{editor.setFieldsValue(index==null?{name:'',prompt:''}:(values[g.custom]||[])[index]);setEditing({g,index});};
 const active=groups.some(g=>(values[g.field]||g.defaults).length+(values[g.custom]||[]).length>0);
 return <>{groups.map(g=><Form.Item key={g.custom} name={g.custom} hidden><Input/></Form.Item>)}<Collapse defaultActiveKey={[groups[0].field]} items={groups.map(g=>{const selected=values[g.field]||g.defaults,custom=values[g.custom]||[],count=selected.length+custom.length;return {key:g.field,forceRender:true,label:<Space><Typography.Text strong>{g.title}</Typography.Text><Typography.Text type="secondary">{count?'已选 '+count+' 项':'未配置'}</Typography.Text></Space>,children:<><Form.Item name={g.field} initialValue={g.defaults}><Checkbox.Group options={g.options}/></Form.Item><Space style={{display:'flex',justifyContent:'space-between',margin:'16px 0'}}><Typography.Text strong>自定义规则</Typography.Text><Button onClick={()=>open(g,null)}>添加规则</Button></Space>{custom.length>0&&<Table size="small" pagination={false} tableLayout="fixed" scroll={{x:620}} dataSource={custom.map((r,i)=>({...r,key:i}))} columns={[{title:'规则名称',dataIndex:'name',width:160},{title:'增强 Prompt',dataIndex:'prompt',render:value=><Typography.Paragraph style={{margin:0,overflowWrap:'anywhere'}} ellipsis={{rows:2,tooltip:value}}>{value}</Typography.Paragraph>},{title:'操作',width:150,render:(_,r)=><Space size={4} style={{whiteSpace:'nowrap'}}><Button type="link" style={{whiteSpace:'nowrap'}} onClick={()=>open(g,r.key)}>编辑</Button><Button type="link" danger style={{whiteSpace:'nowrap'}} onClick={()=>form.setFieldValue(g.custom,custom.filter((_,i)=>i!==r.key))}>删除</Button></Space>}]}/>}</>};})}/>
 {active&&<div style={{marginTop:20}}><Form.Item name="enhancementModel" label="增强模型" rules={[{required:true}]}><Select placeholder="请选择增强模型" options={['Qwen3-14B','DeepSeek-V3.1'].map(value=>({value,label:value}))}/></Form.Item><Collapse ghost items={[{key:'advanced',label:'高级参数',children:<Form.Item name="enhancementParameters" label="模型参数" rules={[{validator:(_,value)=>{const error=modelParametersError(value,true);return error?Promise.reject(new Error(error)):Promise.resolve();}}]}><Input.TextArea placeholder="请输入合法 JSON，如 {&quot;temperature&quot;:0.7}" rows={3} onChange={()=>form.setFieldValue('enhancementParametersEnabled',true)}/></Form.Item>}]}/></div>}
 <Modal title="自定义增强规则" open={!!editing} onCancel={()=>setEditing(null)} onOk={async()=>{const v=await editor.validateFields(),list=[...(form.getFieldValue(editing.g.custom)||[])];if(editing.index==null)list.push(v);else list[editing.index]=v;form.setFieldValue(editing.g.custom,list);setEditing(null);}}><Form form={editor} layout="vertical"><Form.Item name="name" label="规则名称" rules={[{required:true,whitespace:true}]}><Input placeholder="请输入规则名称"/></Form.Item><Form.Item name="prompt" label="增强 Prompt" rules={[{required:true,whitespace:true}]}><Input.TextArea placeholder="描述增强 Prompt，说明目标、约束和输出要求" rows={5}/></Form.Item></Form></Modal></>;
}
