import React,{useState} from 'react';
import {Button,Checkbox,Collapse,Descriptions,Form,Input,InputNumber,Modal,Select,Space,Table,Tag,Typography,message} from 'antd';
import {qualityConfig,validateQualityConfig,FIXED,PARAMETER,CUSTOM,paramsFor,samplingLabels,fieldRuleInstances} from './qualityCatalog';
const {Text}=Typography;
export const targetOptionsFor=modality=>modality==='文档图像'?['文档图像','标注文件']:modality==='对话文本'?['事件计划','全部消息']:['事件计划','时序字段'];
export function ruleTarget(modality,rule){
 const options=targetOptionsFor(modality),target=rule.target||rule.scope||'';
 if(options.includes(target))return target;
 if(modality==='文档图像')return /图像|整图|图片|视觉|水印|OCR|像素|全白|全黑|画布尺寸/i.test(target+' '+rule.name+' '+rule.method)?'文档图像':'标注文件';
 if(modality==='对话文本')return /事件|指令|采样/.test(target)?'事件计划':'全部消息';
 return /事件|指令|采样/.test(target)?'事件计划':'时序字段';
}
export default function UnifiedQualityEditor({modality,value,onChange,context={},readOnly=false,rules:providedRules}){
 const config=providedRules?{rules:providedRules.map(r=>({...r,id:r.id||r.rule_id,category:r.category||'基础质检',description:r.description||r.content||r.logic,logic:r.logic||r.content||r.description,method:r.method||r.engine})),labels:[]}:qualityConfig(modality,value),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[form]=Form.useForm();
 if(!providedRules)config.rules.push(...fieldRuleInstances(modality,context).filter(r=>!config.rules.some(x=>x.id===r.id)));
 config.rules=config.rules.map(r=>({...r,target:ruleTarget(modality,r)}));
 const commit=next=>{validateQualityConfig(next);onChange?.(next);};
 const patch=(id,changes)=>commit({...config,rules:config.rules.map(r=>r.id===id?{...r,...changes}:r)});
 const open=(r,adding=false)=>{const id=adding?r.id+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6):r.id;const isPrivacyCustom=adding&&r.category==='隐私质检',isGeneralCustom=adding&&r.category==='用户自定义规则',isDocumentCustom=adding&&modality==='文档图像'&&r.configType===CUSTOM,isLabelCustom=adding&&r.category==='标签分类';const defaultTarget=targetOptionsFor(modality)[0];const item={...r,id,originRuleId:r.originRuleId||r.id,example:false,enabled:true,...(isPrivacyCustom||isGeneralCustom||isDocumentCustom||isLabelCustom?{name:'',target:defaultTarget,method:modality==='文档图像'?'VLM模型':'LLM模型',prompt:'',failCriteria:''}:{})};setEditing({rule:item,adding});form.resetFields();form.setFieldsValue({...item,params:Object.fromEntries(paramsFor(r).map(([key,, ,def])=>[key,r.params?.[key]??def])),enums:(config.labels?.find(d=>d.id===r.id)?.values||r.values||[]).join('\n')});};
 const save=async()=>{try{const v=await form.validateFields(),r={...editing.rule,...v};if(r.params?.minChange>r.params?.maxChange)throw Error('最小变化幅度不能大于最大变化幅度');const next={...config,rules:editing.adding?[...config.rules,r]:config.rules.map(x=>x.id===r.id?r:x)};
 if(r.resultType==='statistics'&&r.configType===CUSTOM){const vals=(v.enums||'').split('\n').map(x=>x.trim()).filter(Boolean);next.labels=[...(config.labels||[]).filter(x=>x.id!==r.id),{id:r.id,name:r.name,values:vals,prompt:r.prompt,source:'custom'}];}
 commit(next);setEditing(null);message.success('规则已保存');}catch(e){if(e.message)message.error(e.message);}};
 const matched=config.rules.filter(r=>!search||[r.id,r.name].join(' ').toLowerCase().includes(search.toLowerCase())),visible=matched.filter(r=>!((r.category==='隐私质检'||r.category==='用户自定义规则'||r.category==='标签分类')&&r.example)),groups=[...new Set(matched.map(r=>r.category))];
 const columns=[
 {title:'启用',width:60,render:(_,r)=>r.example?<Text type="secondary">—</Text>:<Checkbox aria-label={'启用'+r.name} disabled={readOnly||r.id==='L13'||r.id==='T10'} checked={r.enabled!==false} onChange={e=>patch(r.id,{enabled:e.target.checked})}/>},
 {title:'规则名称',width:230,render:(_,r)=><><Text strong>{r.name}</Text><div className="muted-id">{r.id}</div></>},
 {title:'检查说明',render:(_,r)=><Text>{r.description}</Text>},
 {title:'检查对象',dataIndex:'target',width:120},
 {title:'检测方式',dataIndex:'method',width:160,render:value=>({function:'规则引擎',semantic:'LLM模型',vlm:'VLM模型'}[value]||value)},
 {title:'操作',width:130,render:(_,r)=>{const privacySystem=r.category==='隐私质检'&&r.configType!==CUSTOM;return <Space wrap><Button type="link" onClick={()=>open(r,r.example)} disabled={readOnly&&r.example}>{r.example?'添加规则':readOnly||r.configType===FIXED||privacySystem?'查看详情':'配置'}</Button>{r.originRuleId&&!r.fieldLinked&&r.configType===CUSTOM&&!readOnly&&<Button type="link" danger onClick={()=>commit({...config,rules:config.rules.filter(x=>x.id!==r.id),labels:config.labels.filter(x=>x.id!==r.id)})}>删除</Button>}</Space>}}
 ];
 const auto=samplingLabels(context,modality),editingPrivacySystem=editing?.rule.category==='隐私质检'&&editing?.rule.configType!==CUSTOM,locked=readOnly||editing?.rule.configType===FIXED||editingPrivacySystem;
 const privacyExample=config.rules.find(r=>r.id==='S18')||{id:'S-CUSTOM',name:'设备标识关联隐私',category:'隐私质检',configType:CUSTOM,resultType:'binary',method:modality==='文档图像'?'VLM模型':'LLM模型',target:modality==='文档图像'?'文档图像':'样本内容',logic:'依据用户填写的检测 Prompt / 规则条件识别隐私风险。',description:'用户定义隐私检查规则。'};
 const privacyTargets=targetOptionsFor(modality);
 const customExample=config.rules.find(r=>r.example&&r.category==='用户自定义规则'&&r.id===(modality==='文档图像'?'D15':modality==='对话文本'?'L26':'T14'))||{id:'CUSTOM',name:'自定义规则',category:'用户自定义规则',configType:CUSTOM,resultType:'binary',method:modality==='文档图像'?'VLM模型':'LLM模型',target:modality==='文档图像'?'文档图像':'样本内容',logic:'依据用户填写的检测 Prompt / 规则条件进行判断。',description:'用户新增的自定义质检规则。'};
 const labelExample=config.rules.find(r=>r.configType===CUSTOM&&r.resultType==='statistics')||{id:'T-LABEL',name:'用户自定义标签',category:'标签分类',configType:CUSTOM,resultType:'statistics',method:modality==='文档图像'?'VLM模型':'LLM模型',target:modality==='文档图像'?'文档图像':'样本',logic:'按自定义枚举及 Prompt 分类，不计质量分。',description:'用户配置标签维度、枚举值、检查对象及打标 Prompt。'};
 return <div className="unified-quality-editor"><Input.Search aria-label="搜索质检规则" placeholder="搜索规则名称或编号" allowClear value={search} onChange={e=>setSearch(e.target.value)} style={{maxWidth:360,marginBottom:16}}/>
 <Collapse defaultActiveKey={['文档基础质检','时序结构与数值','正文与回答质量','指令匹配度与事件一致性','事件与工具对话一致性检查','特定内容与字典比对（按模板启用）','用户自定义规则','标签分类']} items={groups.map(category=>{const categoryRules=config.rules.filter(r=>r.category===category&&!r.example),enabledCount=categoryRules.filter(r=>r.enabled!==false).length,displayCategory=category==='用户自定义规则'?'自定义规则':category;return {key:category,label:<div style={{display:'flex',alignItems:'center',justifyContent:'space-between',width:'100%',paddingRight:8}}><span>{displayCategory} · {enabledCount}/{categoryRules.length}</span>{category==='隐私质检'&&!readOnly&&<Button size="small" type="primary" onClick={event=>{event.stopPropagation();open(privacyExample,true);}}>添加自定义规则</Button>}{category==='用户自定义规则'&&!readOnly&&<Button size="small" type="primary" onClick={event=>{event.stopPropagation();open(customExample,true);}}>添加规则</Button>}{(category==='标签分类')&&!readOnly&&<Button size="small" type="primary" onClick={event=>{event.stopPropagation();open(labelExample,true);}}>添加标签</Button>}</div>,children:<>
 {category==='隐私质检'&&<Text type="secondary" style={{display:'block',marginBottom:12}}>隐私质检会在上传数据集和模板发布时启动检查，不检查经过平台受控合成的数据集。</Text>}
 {(category==='标签分类')&&<Text type="secondary" style={{display:'block',marginBottom:12}}>标签仅用于统计各类型数据覆盖率，为定向扩增提供依据，非质量检测。</Text>}
 {((category==='标签分类'&&modality==='时序数据')||(category==='指令匹配度与事件一致性'&&modality==='对话文本'))&&<div style={{marginBottom:16}}><Text strong>系统自动打标</Text><div className="form-help">{auto.length?auto.map(d=>d.name+'：'+d.values.join('、')).join('；'):'请先配置事件采样维度'}</div></div>}
 <Table rowKey="id" size="small" pagination={{pageSize:12,hideOnSinglePage:true}} columns={columns} dataSource={visible.filter(r=>r.category===category)} scroll={{x:850}}/></>}})}/>
 <Modal title={editing?.adding&&editing?.rule.category==='隐私质检'?'添加自定义隐私规则':editing?.adding&&editing?.rule.category==='用户自定义规则'?(editing.rule.resultType==='statistics'?'添加标签':'添加自定义规则'):editing?.adding&&editing?.rule.category==='标签分类'?'添加标签':editing?.rule.name} open={!!editing} onCancel={()=>setEditing(null)} onOk={save} width={720} footer={locked?<Button onClick={()=>setEditing(null)}>关闭</Button>:undefined} destroyOnHidden>
 {editing&&<Form form={form} layout="vertical" key={editing.rule.id}><Descriptions size="small" column={1} items={[{key:'id',label:'规则编号',children:editing.rule.id},{key:'target',label:'检查对象',children:editing.rule.target},{key:'method',label:'检测方式',children:editing.rule.method},{key:'logic',label:'检查说明',children:editing.rule.logic}]}/>
 {editing.rule.configType===CUSTOM&&!readOnly&&<><Form.Item name="name" label="规则名称" rules={[{required:true,whitespace:true}]}><Input placeholder={editing.rule.category==='隐私质检'?'例如：设备标识关联隐私':'请输入规则或标签维度名称'}/></Form.Item><Form.Item name="target" label="检查对象" rules={[{required:true}]}><Select placeholder={"请选择检查对象"} options={privacyTargets.map(value=>({value,label:value}))} onChange={target=>{if(modality==='文档图像')form.setFieldValue('method',target==='文档图像'?'VLM模型':'LLM模型');}}/></Form.Item><Form.Item name="method" label="检测方式"><Select placeholder={"请选择检测方式"} options={(modality==='文档图像'?['VLM模型','LLM模型']:editing.rule.category==='隐私质检'?['LLM模型']:['LLM模型','规则引擎']).map(value=>({value,label:value}))}/></Form.Item><Form.Item name="prompt" label={editing.rule.resultType==='statistics'?'打标 Prompt':'检测 Prompt / 规则条件'} extra={editing.rule.category==='隐私质检'?'可在此描述需要匹配的格式、正则或语义判断条件。':undefined} rules={[{required:true,whitespace:true}]}><Input.TextArea rows={4} placeholder={editing.rule.category==='隐私质检'?'例如：识别可关联到具体主体的设备标识；也可填写编号格式或正则条件。':'说明检测或分类依据、约束及输出要求'}/></Form.Item>{editing.rule.resultType==='statistics'?<Form.Item name="enums" label="标签枚举值（每行一个）" rules={[{required:true}]}><Input.TextArea placeholder={"填写允许的取值，每行一个"} rows={4}/></Form.Item>:<Form.Item name="failCriteria" label="不通过条件" rules={[{required:true,whitespace:true}]}><Input.TextArea placeholder={"请输入不通过条件"} rows={3}/></Form.Item>}</>}
 {editing.rule.configType===PARAMETER&&!editingPrivacySystem&&<Form.Item name="target" label="检查对象" rules={[{required:true}]}><Select placeholder={"请选择检查对象"} disabled={readOnly} options={privacyTargets.map(value=>({value,label:value}))}/></Form.Item>}
 {editing.rule.configType===PARAMETER&&!editingPrivacySystem&&paramsFor(editing.rule).map(([key,label,type])=><Form.Item key={key} name={['params',key]} label={label} rules={[{required:true},{validator:(_,v)=>type==='text'||Number.isFinite(v)&&(type==='signed'||v>=0)&&(type!=='integer'||Number.isInteger(v))&&(type!=='ratio'||v<=1)?Promise.resolve():Promise.reject(Error('请输入有效参数'))}]}>{type==='text'?<Input placeholder={`请输入${label}`} disabled={readOnly}/>:<InputNumber placeholder={`请输入${label}`} disabled={readOnly} style={{width:'100%'}} min={type==='signed'?undefined:0} max={type==='ratio'?1:undefined} precision={type==='integer'?0:undefined}/>}</Form.Item>)}
 {locked&&editing.rule.configType===CUSTOM&&<Descriptions column={1} items={[{key:'prompt',label:'Prompt',children:editing.rule.prompt},{key:'fail',label:'不通过条件',children:editing.rule.failCriteria}]}/>}
 </Form>}</Modal></div>;
}
export function FormQualityEditor({form,modality,onManualChange,readOnly}){
 const value=Form.useWatch('qualityCatalog',{form,preserve:true}),all=Form.useWatch([],{form,preserve:true})||form.getFieldsValue(true);
 const context={fields:all.fields||[],sampler:all.sampler||{dimensions:all.samplingDimensions||[]},event_generation:{sampling_dimensions:all.eventDimensions||[]}};
 return <><Form.Item name="qualityCatalog" hidden><Input/></Form.Item><UnifiedQualityEditor readOnly={readOnly} modality={modality} value={value} context={context} onChange={v=>{form.setFieldValue('qualityCatalog',v);onManualChange?.();}}/></>;
}
